export const growthProfileStyles = {
  page: "mx-auto grid max-w-[1500px] gap-6 pb-16",
  hero: "grid gap-[clamp(2rem,6vw,6rem)] overflow-hidden rounded-[2rem] border border-white/[.06] [background:radial-gradient(circle_at_10%_0%,rgba(139,92,246,.2),transparent_30rem),radial-gradient(circle_at_90%_100%,rgba(6,182,212,.1),transparent_28rem),#070708] p-[clamp(2rem,6vw,5rem)] lg:grid-cols-[1.2fr_.8fr] [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[.15em] [&_span]:text-violet-300 [&_h1]:mt-4 [&_h1]:max-w-[16ch] [&_h1]:text-[clamp(2.7rem,6vw,5.3rem)] [&_h1]:font-semibold [&_h1]:leading-[.98] [&_h1]:tracking-tight [&_p]:max-w-2xl [&_p]:text-sm [&_p]:leading-7 [&_p]:text-white/50 [&_dl]:m-0 [&_dl]:grid [&_dl]:content-center [&_dl]:gap-2 [&_dl_div]:grid [&_dl_div]:grid-cols-2 [&_dl_div]:rounded-2xl [&_dl_div]:border [&_dl_div]:border-white/[.05] [&_dl_div]:bg-white/[.025] [&_dl_div]:p-4 [&_dt]:text-[10px] [&_dt]:uppercase [&_dt]:tracking-[.12em] [&_dt]:text-white/35 [&_dd]:m-0 [&_dd]:text-right [&_dd]:text-sm [&_dd]:font-semibold",
  nextStep: "flex flex-wrap items-center gap-6 rounded-3xl border border-cyan-300/15 bg-cyan-300/[.035] p-[clamp(1.5rem,4vw,3rem)] [&>div]:mr-auto [&_span]:text-[9px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[.14em] [&_span]:text-cyan-300 [&_h2]:mt-3 [&_h2]:text-2xl [&_h2]:font-semibold [&_p]:mb-0 [&_p]:max-w-2xl [&_p]:text-sm [&_p]:text-white/45 [&_a]:rounded-full [&_a]:bg-white [&_a]:px-5 [&_a]:py-3 [&_a]:text-xs [&_a]:font-semibold [&_a]:text-black",
  grid: "grid gap-4 md:grid-cols-2 xl:grid-cols-3 [&>article]:rounded-3xl [&>article]:border [&>article]:border-white/[.06] [&>article]:bg-card/60 [&>article]:p-6 [&_article>header]:flex [&_article>header]:items-start [&_article>header]:justify-between [&_article>header]:gap-4 [&_article>header_span]:text-base [&_article>header_span]:font-semibold [&_article>header_strong]:rounded-full [&_article>header_strong]:border [&_article>header_strong]:border-violet-400/15 [&_article>header_strong]:bg-violet-400/[.06] [&_article>header_strong]:px-2.5 [&_article>header_strong]:py-1 [&_article>header_strong]:text-[9px] [&_article>header_strong]:font-semibold [&_article>header_strong]:uppercase [&_article>header_strong]:tracking-[.1em] [&_article>header_strong]:text-violet-300 [&_article>p]:min-h-12 [&_article>p]:text-xs [&_article>p]:leading-6 [&_article>p]:text-white/45 [&_article>dl]:grid [&_article>dl]:grid-cols-3 [&_article>dl]:gap-2 [&_article>dl_div]:rounded-xl [&_article>dl_div]:bg-black/20 [&_article>dl_div]:p-3 [&_dt]:text-[8px] [&_dt]:uppercase [&_dt]:tracking-[.1em] [&_dt]:text-white/30 [&_dd]:m-0 [&_dd]:mt-1 [&_dd]:text-xs [&_dd]:font-medium [&_details]:mt-5 [&_summary]:cursor-pointer [&_summary]:text-xs [&_summary]:text-cyan-200/70 [&_ol]:grid [&_ol]:list-none [&_ol]:gap-2 [&_ol]:p-0 [&_li]:grid [&_li]:grid-cols-[1fr_auto] [&_li]:gap-1 [&_li]:rounded-xl [&_li]:bg-black/20 [&_li]:p-3 [&_li_span]:text-[9px] [&_li_span]:text-white/45 [&_li_strong]:text-xs [&_li_small]:col-span-2 [&_li_small]:text-[9px] [&_li_small]:text-white/25 [&_article>small]:mt-5 [&_article>small]:block [&_article>small]:text-xs [&_article>small]:leading-6 [&_article>small]:text-white/30",
  progress: "my-5 h-2 overflow-hidden rounded-full bg-black/40 [&>span]:block [&>span]:h-full [&>span]:rounded-full [&>span]:bg-gradient-to-r [&>span]:from-violet-400 [&>span]:to-cyan-300",
  state: "mx-auto min-h-[60vh] max-w-[1500px] rounded-[2rem] border border-white/[.06] bg-card/60 p-[clamp(2rem,6vw,5rem)] [&_span]:text-[10px] [&_span]:uppercase [&_span]:tracking-[.14em] [&_span]:text-violet-300 [&_h1]:mt-4 [&_h1]:text-[clamp(2.5rem,5vw,4.5rem)] [&_h1]:font-semibold [&_p]:text-sm [&_p]:text-white/50 [&_div]:mt-3 [&_div]:h-20 [&_div]:animate-pulse [&_div]:rounded-2xl [&_div]:bg-white/[.04] [&_button]:rounded-full [&_button]:border-0 [&_button]:bg-white [&_button]:px-5 [&_button]:py-3 [&_button]:text-xs [&_button]:font-semibold [&_button]:text-black",
} as const;

