export const verificationDetailStyles = {
  page: "mx-auto max-w-[1500px] space-y-6 pb-16",
  header:
    "relative flex flex-wrap items-center gap-4 rounded-3xl border border-white/[0.06] bg-card/60 p-4 shadow-[0_30px_60px_-15px_rgba(0,0,0,0.5),0_0_0_1px_rgba(255,255,255,0.02)] backdrop-blur-md max-[700px]:items-start",
  caseIdentity:
    "mr-auto grid min-w-0 gap-1 px-2 [&_span]:font-sans [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[0.14em] [&_span]:text-violet-400 [&_strong]:truncate [&_strong]:font-mono [&_strong]:text-xs [&_strong]:font-medium [&_strong]:text-white/70",
  status:
    "grid gap-1 rounded-2xl border border-white/[0.05] bg-white/[0.025] px-4 py-2 text-right [&_span]:font-sans [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[0.12em] [&_span]:text-white/35 [&_strong]:font-sans [&_strong]:text-xs [&_strong]:font-medium [&_strong]:text-white/75 data-[status=COMPLETED]:border-emerald-500/20 data-[status=COMPLETED]:bg-emerald-500/[0.06] data-[status=PARTIALLY_COMPLETED]:border-amber-400/20 data-[status=PARTIALLY_COMPLETED]:bg-amber-400/[0.06] data-[status=FAILED]:border-danger/20 data-[status=FAILED]:bg-danger/[0.06]",
  actions:
    "flex flex-wrap gap-2 [&_button]:rounded-full [&_button]:border [&_button]:border-white/10 [&_button]:bg-white/[0.04] [&_button]:px-4 [&_button]:py-2.5 [&_button]:font-sans [&_button]:text-xs [&_button]:font-medium [&_button]:text-white/70 [&_button]:transition-all [&_button]:duration-200 [&_button:hover]:border-white/15 [&_button:hover]:bg-white/[0.08] [&_button:active]:scale-[0.98] [&_button:disabled]:pointer-events-none [&_button:disabled]:opacity-50 [&_a]:rounded-full [&_a]:border [&_a]:border-white/10 [&_a]:bg-white/[0.04] [&_a]:px-4 [&_a]:py-2.5 [&_a]:font-sans [&_a]:text-xs [&_a]:font-medium [&_a]:text-white/70 [&_a]:transition-colors [&_a:hover]:border-violet-400/30 [&_a:hover]:text-violet-300 [&_button[data-variant=primary]]:border-0 [&_button[data-variant=primary]]:bg-gradient-to-r [&_button[data-variant=primary]]:from-[#C084FC] [&_button[data-variant=primary]]:to-[#6366F1] [&_button[data-variant=primary]]:text-white [&_button[data-variant=primary]:hover]:shadow-[0_12px_28px_-10px_rgba(139,92,246,0.4)] [&_button[data-variant=danger]]:border-danger/20 [&_button[data-variant=danger]]:bg-danger/[0.06] [&_button[data-variant=danger]]:text-red-300 [&_button[data-variant=danger]:hover]:bg-danger/10",
  summary:
    "relative grid grid-cols-[minmax(0,1.25fr)_minmax(18rem,0.45fr)] gap-[clamp(2rem,6vw,6rem)] overflow-hidden rounded-3xl border border-white/[0.06] [background:radial-gradient(circle_at_12%_0%,rgba(139,92,246,0.2),transparent_30rem),#070708] p-[clamp(2rem,6vw,5rem)] shadow-[0_30px_60px_-15px_rgba(0,0,0,0.5)] max-[800px]:grid-cols-1 [&>div>span]:font-sans [&>div>span]:text-[10px] [&>div>span]:font-semibold [&>div>span]:uppercase [&>div>span]:tracking-[0.18em] [&>div>span]:text-violet-400 [&_h1]:my-5 [&_h1]:max-w-[18ch] [&_h1]:font-sans [&_h1]:text-[clamp(2.5rem,5vw,4.75rem)] [&_h1]:leading-[1.02] [&_h1]:font-semibold [&_h1]:tracking-tighter [&_p]:max-w-2xl [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/50 [&_dl]:m-0 [&_dl]:grid [&_dl]:content-start [&_dl]:gap-2 [&_dl_div]:grid [&_dl_div]:grid-cols-2 [&_dl_div]:gap-4 [&_dl_div]:rounded-2xl [&_dl_div]:border [&_dl_div]:border-white/[0.04] [&_dl_div]:bg-white/[0.025] [&_dl_div]:px-4 [&_dl_div]:py-3 [&_dt]:font-sans [&_dt]:text-[10px] [&_dt]:font-semibold [&_dt]:uppercase [&_dt]:tracking-[0.12em] [&_dt]:text-white/35 [&_dd]:m-0 [&_dd]:break-all [&_dd]:text-right [&_dd]:font-mono [&_dd]:text-[11px] [&_dd]:text-white/70",
  processingGrid:
    "grid grid-cols-[minmax(17rem,0.42fr)_minmax(0,1fr)] gap-6 max-[850px]:grid-cols-1",
  stagePanel:
    "relative overflow-hidden rounded-3xl border border-violet-400/15 [background:radial-gradient(circle_at_0%_0%,rgba(139,92,246,0.18),transparent_24rem),rgba(7,7,8,0.82)] p-[clamp(1.5rem,4vw,3rem)] shadow-[0_30px_60px_-15px_rgba(0,0,0,0.5)]",
  eventPanel:
    "relative min-w-0 overflow-hidden rounded-3xl border border-white/[0.06] bg-card/60 p-[clamp(1.5rem,4vw,3rem)] shadow-[0_30px_60px_-15px_rgba(0,0,0,0.5)]",
  panelHeader:
    "mb-6 flex items-center justify-between gap-4 font-sans text-[10px] font-semibold uppercase tracking-[0.14em] text-white/35 [&>span:last-child]:rounded-full [&>span:last-child]:border [&>span:last-child]:border-violet-400/20 [&>span:last-child]:bg-violet-400/[0.06] [&>span:last-child]:px-2.5 [&>span:last-child]:py-1 [&>span:last-child]:text-violet-300",
  progress:
    "mb-7 h-2 overflow-hidden rounded-full bg-black/40 shadow-inner [&>span]:block [&>span]:h-full [&>span]:rounded-full [&>span]:bg-gradient-to-r [&>span]:from-[#C084FC] [&>span]:via-[#8B5CF6] [&>span]:to-[#06B6D4] [&>span]:shadow-[0_0_18px_rgba(139,92,246,0.55)] [&>span]:transition-[width] [&>span]:duration-700",
  stageRail:
    "m-0 grid list-none gap-2 p-0 [&_li]:grid [&_li]:grid-cols-[2rem_1fr_auto] [&_li]:items-center [&_li]:gap-3 [&_li]:rounded-2xl [&_li]:border [&_li]:border-white/[0.035] [&_li]:bg-white/[0.015] [&_li]:px-3 [&_li]:py-3 [&_li]:transition-all [&_span]:font-mono [&_span]:text-[10px] [&_span]:text-white/30 [&_small]:rounded-full [&_small]:px-2 [&_small]:py-1 [&_small]:font-sans [&_small]:text-[9px] [&_small]:font-semibold [&_small]:uppercase [&_small]:tracking-[0.1em] [&_small]:text-white/30 [&_strong]:font-sans [&_strong]:text-xs [&_strong]:font-medium [&_strong]:text-white/70 [&_li[data-state=pending]]:opacity-40 [&_li[data-state=active]]:border-violet-400/25 [&_li[data-state=active]]:bg-violet-400/[0.07] [&_li[data-state=active]]:shadow-[0_10px_30px_-18px_rgba(139,92,246,0.8)] [&_li[data-state=active]_span]:text-violet-300 [&_li[data-state=active]_small]:bg-violet-400/10 [&_li[data-state=active]_small]:text-violet-300 [&_li[data-state=complete]_span]:text-emerald-400 [&_li[data-state=complete]_small]:bg-emerald-400/[0.06] [&_li[data-state=complete]_small]:text-emerald-400",
  events:
    "m-0 grid list-none gap-3 p-0 [&_li]:grid [&_li]:grid-cols-[3rem_1fr] [&_li]:gap-4 [&_li]:rounded-2xl [&_li]:border [&_li]:border-white/[0.04] [&_li]:bg-white/[0.018] [&_li]:p-4 [&_li]:transition-colors [&_li:hover]:bg-white/[0.035] max-[650px]:[&_li]:grid-cols-[2.5rem_1fr] [&_span]:font-mono [&_span]:text-[10px] [&_span]:text-violet-300 [&_small]:font-mono [&_small]:text-[10px] [&_small]:text-white/30 [&_strong]:font-sans [&_strong]:text-sm [&_strong]:font-medium [&_strong]:capitalize [&_strong]:text-white/75 [&_p]:my-1 [&_p]:font-sans [&_p]:text-xs [&_p]:leading-relaxed [&_p]:text-white/45",
  eventError:
    "rounded-2xl border border-danger/20 bg-danger/[0.06] p-4 text-sm text-red-200 [&_p]:mt-0 [&_button]:rounded-full [&_button]:border [&_button]:border-danger/25 [&_button]:bg-danger/10 [&_button]:px-4 [&_button]:py-2 [&_button]:font-sans [&_button]:text-xs [&_button]:font-medium [&_button]:text-red-200 [&_button]:transition-colors [&_button:hover]:bg-danger/15",
  failure:
    "rounded-3xl border border-danger/20 bg-danger/[0.055] p-[clamp(2rem,5vw,4rem)] shadow-[0_30px_60px_-15px_rgba(0,0,0,0.45)] [&>span]:font-sans [&>span]:text-[10px] [&>span]:font-semibold [&>span]:uppercase [&>span]:tracking-[0.14em] [&>span]:text-red-300 [&_h2]:mt-4 [&_h2]:font-sans [&_h2]:text-[clamp(2rem,4vw,3.5rem)] [&_h2]:font-semibold [&_h2]:tracking-tighter [&_p]:max-w-2xl [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/50",
  complete:
    "rounded-3xl border border-emerald-400/20 bg-emerald-400/[0.045] p-[clamp(2rem,5vw,4rem)] shadow-[0_30px_60px_-15px_rgba(0,0,0,0.45)] [&>span]:font-sans [&>span]:text-[10px] [&>span]:font-semibold [&>span]:uppercase [&>span]:tracking-[0.14em] [&>span]:text-emerald-400 [&_h2]:mt-4 [&_h2]:font-sans [&_h2]:text-[clamp(2rem,4vw,3.5rem)] [&_h2]:font-semibold [&_h2]:tracking-tighter [&_p]:max-w-2xl [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/50",
  loading:
    "mx-auto min-h-[70svh] max-w-[1500px] rounded-3xl border border-white/[0.06] bg-card/60 p-[clamp(2rem,6vw,5rem)] shadow-[0_30px_60px_-15px_rgba(0,0,0,0.5)] [&>span]:font-mono [&>span]:text-[10px] [&>span]:uppercase [&>span]:tracking-[0.14em] [&>span]:text-violet-400 [&_h1]:mt-4 [&_h1]:font-sans [&_h1]:text-[clamp(2.5rem,5vw,4.75rem)] [&_h1]:font-semibold [&_h1]:tracking-tighter [&_div]:mt-3 [&_div]:h-20 [&_div]:animate-pulse [&_div]:rounded-2xl [&_div]:bg-white/[0.05]",
  error:
    "mx-auto min-h-[70svh] max-w-[1500px] rounded-3xl border border-danger/20 bg-card/60 p-[clamp(2rem,6vw,5rem)] shadow-[0_30px_60px_-15px_rgba(0,0,0,0.5)] [&>span]:font-sans [&>span]:text-[10px] [&>span]:font-semibold [&>span]:uppercase [&>span]:tracking-[0.14em] [&>span]:text-red-300 [&_h1]:mt-4 [&_h1]:font-sans [&_h1]:text-[clamp(2.5rem,5vw,4.75rem)] [&_h1]:font-semibold [&_h1]:tracking-tighter [&_p]:max-w-2xl [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/50 [&_button]:mr-2 [&_button]:rounded-full [&_button]:border-0 [&_button]:bg-gradient-to-r [&_button]:from-[#C084FC] [&_button]:to-[#6366F1] [&_button]:px-5 [&_button]:py-3 [&_button]:font-sans [&_button]:text-xs [&_button]:font-medium [&_button]:text-white [&_a]:rounded-full [&_a]:border [&_a]:border-white/10 [&_a]:bg-white/[0.04] [&_a]:px-5 [&_a]:py-3 [&_a]:font-sans [&_a]:text-xs [&_a]:font-medium [&_a]:text-white/70",
  dialogBackdrop:
    "fixed inset-0 z-[100] flex items-center justify-center bg-black/75 p-4 backdrop-blur-md",
  dialog:
    "w-full max-w-[40rem] rounded-3xl border border-white/[0.08] bg-[#0F1012] p-[clamp(1.5rem,4vw,3rem)] shadow-[0_36px_100px_-24px_rgba(0,0,0,0.9),0_0_50px_rgba(139,92,246,0.08)] [&_header]:flex [&_header]:items-center [&_header]:justify-between [&_header]:gap-4 [&_header_span]:truncate [&_header_span]:font-mono [&_header_span]:text-[10px] [&_header_span]:uppercase [&_header_span]:tracking-[0.12em] [&_header_span]:text-white/35 [&_header_button]:grid [&_header_button]:size-10 [&_header_button]:place-items-center [&_header_button]:rounded-full [&_header_button]:border [&_header_button]:border-white/10 [&_header_button]:bg-white/[0.04] [&_header_button]:text-xl [&_header_button]:text-white/50 [&_header_button]:transition-colors [&_header_button:hover]:bg-white/[0.08] [&_header_button:hover]:text-white [&_h2]:mt-7 [&_h2]:font-sans [&_h2]:text-[clamp(2rem,5vw,3.25rem)] [&_h2]:font-semibold [&_h2]:leading-[1.08] [&_h2]:tracking-tighter [&>p]:max-w-2xl [&>p]:text-sm [&>p]:leading-relaxed [&>p]:text-white/50 [&_footer]:mt-8 [&_footer]:flex [&_footer]:flex-wrap [&_footer]:justify-end [&_footer]:gap-2 [&_footer_button]:rounded-full [&_footer_button]:border [&_footer_button]:border-white/10 [&_footer_button]:bg-white/[0.04] [&_footer_button]:px-5 [&_footer_button]:py-3 [&_footer_button]:font-sans [&_footer_button]:text-xs [&_footer_button]:font-medium [&_footer_button]:text-white/70 [&_footer_button]:transition-all [&_footer_button:hover]:border-white/15 [&_footer_button:hover]:bg-white/[0.08] [&_footer_button:active]:scale-[0.98] [&_footer_button:disabled]:pointer-events-none [&_footer_button:disabled]:opacity-50 [&_footer_button[data-danger=true]]:border-danger/25 [&_footer_button[data-danger=true]]:bg-danger/10 [&_footer_button[data-danger=true]]:text-red-200 [&_footer_button[data-danger=true]:hover]:bg-danger/15 [&_footer_button[data-danger=false]]:border-0 [&_footer_button[data-danger=false]]:bg-gradient-to-r [&_footer_button[data-danger=false]]:from-[#C084FC] [&_footer_button[data-danger=false]]:to-[#6366F1] [&_footer_button[data-danger=false]]:text-white",
  dialogError:
    "!rounded-2xl !border !border-danger/20 !bg-danger/[0.06] !p-4 !text-sm !text-red-200",
} as const;
