export const guidedInvestigationStyles = {
	panel: "grid gap-6 overflow-hidden rounded-[2rem] border border-cyan-300/15 [background:radial-gradient(circle_at_10%_0%,rgba(6,182,212,.12),transparent_26rem),radial-gradient(circle_at_90%_100%,rgba(139,92,246,.13),transparent_28rem),#070708] p-[clamp(1.25rem,4vw,3rem)] [&>header]:grid [&>header]:gap-5 md:[&>header]:grid-cols-[1.1fr_.9fr] [&>header_span]:text-[10px] [&>header_span]:font-semibold [&>header_span]:uppercase [&>header_span]:tracking-[.15em] [&>header_span]:text-cyan-300 [&>header_h2]:mt-3 [&>header_h2]:max-w-[18ch] [&>header_h2]:text-[clamp(2rem,4vw,3.6rem)] [&>header_h2]:font-semibold [&>header_h2]:leading-[1.05] [&>header_h2]:tracking-tight [&>header_p]:m-0 [&>header_p]:self-end [&>header_p]:text-sm [&>header_p]:leading-7 [&>header_p]:text-white/50",
	questions: "grid gap-4 [&_fieldset]:m-0 [&_fieldset]:grid [&_fieldset]:gap-3 [&_fieldset]:rounded-3xl [&_fieldset]:border [&_fieldset]:border-white/[.06] [&_fieldset]:bg-black/20 [&_fieldset]:p-[clamp(1.25rem,3vw,2rem)] [&_legend]:grid [&_legend]:gap-2 [&_legend]:px-1 [&_legend]:text-base [&_legend]:font-medium [&_legend]:leading-7 [&_legend_span]:text-[9px] [&_legend_span]:font-semibold [&_legend_span]:uppercase [&_legend_span]:tracking-[.14em] [&_legend_span]:text-violet-300 [&_fieldset>div]:grid [&_fieldset>div]:gap-2 [&_label]:flex [&_label]:cursor-pointer [&_label]:items-start [&_label]:gap-3 [&_label]:rounded-2xl [&_label]:border [&_label]:border-white/[.05] [&_label]:bg-white/[.02] [&_label]:p-4 [&_label]:text-sm [&_label]:text-white/65 [&_label]:transition-colors [&_label:has(input:checked)]:border-violet-400/30 [&_label:has(input:checked)]:bg-violet-400/[.08] [&_input]:mt-1 [&_input]:accent-violet-400 [&_textarea]:min-h-28 [&_textarea]:resize-y [&_textarea]:rounded-2xl [&_textarea]:border [&_textarea]:border-white/10 [&_textarea]:bg-black/30 [&_textarea]:p-4 [&_textarea]:text-sm [&_textarea]:text-white [&_textarea]:outline-none [&_textarea:focus]:border-cyan-300/35 [&>button]:justify-self-start [&>button]:rounded-full [&>button]:border-0 [&>button]:bg-gradient-to-r [&>button]:from-violet-400 [&>button]:to-indigo-500 [&>button]:px-6 [&>button]:py-3 [&>button]:text-sm [&>button]:font-semibold [&>button]:text-white [&>button:disabled]:opacity-50",
	feedbackGrid: "grid gap-3 md:grid-cols-2 [&_article]:rounded-3xl [&_article]:border [&_article]:border-white/[.06] [&_article]:bg-white/[.025] [&_article]:p-6 [&_article_span]:text-[9px] [&_article_span]:font-semibold [&_article_span]:uppercase [&_article_span]:tracking-[.12em] [&_article_span]:text-cyan-300 [&_article_h3]:mt-3 [&_article_h3]:text-xl [&_article_h3]:font-semibold [&_article_p]:mb-0 [&_article_p]:text-sm [&_article_p]:leading-7 [&_article_p]:text-white/50",
	loading: "rounded-[2rem] border border-cyan-300/15 bg-cyan-300/[.035] p-[clamp(2rem,5vw,4rem)] [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[.15em] [&_span]:text-cyan-300 [&_h2]:mt-4 [&_h2]:text-3xl [&_h2]:font-semibold [&_p]:max-w-2xl [&_p]:text-sm [&_p]:leading-7 [&_p]:text-white/45",
	error: "rounded-[2rem] border border-amber-300/15 bg-amber-300/[.035] p-[clamp(2rem,5vw,4rem)] [&_span]:text-[10px] [&_span]:uppercase [&_span]:tracking-[.14em] [&_span]:text-amber-200 [&_h2]:mt-4 [&_h2]:text-2xl [&_p]:text-sm [&_p]:text-white/50 [&_button]:rounded-full [&_button]:border [&_button]:border-white/10 [&_button]:bg-white/[.05] [&_button]:px-4 [&_button]:py-2.5 [&_button]:text-xs",
	formError: "m-0 rounded-2xl border border-red-300/20 bg-red-300/[.05] p-4 text-sm text-red-200",
} as const;

