export const reportStyles = {
  report: "grid gap-6",
  modeNavigation:
    "flex flex-wrap items-center gap-5 rounded-3xl border border-white/[.06] bg-card/70 p-3 pl-5 [&>div:first-child]:mr-auto [&>div:first-child]:grid [&>div:first-child]:gap-1 [&>div:first-child_span]:text-[9px] [&>div:first-child_span]:font-semibold [&>div:first-child_span]:uppercase [&>div:first-child_span]:tracking-[.14em] [&>div:first-child_span]:text-violet-300 [&>div:first-child_strong]:text-xs [&>div:first-child_strong]:font-medium [&>div:first-child_strong]:text-white/50 [&>div:last-child]:flex [&>div:last-child]:gap-1 [&_button]:rounded-full [&_button]:border [&_button]:border-transparent [&_button]:bg-transparent [&_button]:px-4 [&_button]:py-2.5 [&_button]:text-xs [&_button]:font-semibold [&_button]:capitalize [&_button]:text-white/45 [&_button]:transition-all [&_button[data-active=true]]:border-violet-400/20 [&_button[data-active=true]]:bg-violet-400/[.1] [&_button[data-active=true]]:text-violet-200 max-sm:[&>div:last-child]:w-full max-sm:[&_button]:flex-1",
  modeOverview:
    "rounded-3xl border border-white/[.06] [background:radial-gradient(circle_at_0%_0%,rgba(139,92,246,.14),transparent_28rem),#070708] p-[clamp(2rem,5vw,4rem)] [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[.14em] [&_span]:text-violet-300 [&_h2]:mt-4 [&_h2]:max-w-[18ch] [&_h2]:text-[clamp(2.3rem,5vw,4rem)] [&_h2]:font-semibold [&_h2]:leading-[1.05] [&_p]:max-w-3xl [&_p]:text-sm [&_p]:leading-7 [&_p]:text-white/50 [&_small]:text-xs [&_small]:text-cyan-200/60",
  learnBreakdown:
    "grid gap-3 md:grid-cols-3 [&>div]:rounded-3xl [&>div]:border [&>div]:border-white/[.06] [&>div]:bg-white/[.02] [&>div]:p-6 [&_span]:text-[9px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[.12em] [&_span]:text-cyan-300 [&_strong]:mt-3 [&_strong]:block [&_strong]:text-4xl [&_strong]:font-semibold [&_p]:mb-0 [&_p]:text-xs [&_p]:leading-6 [&_p]:text-white/45",
  simpleSummary:
    "grid gap-3 lg:grid-cols-3 [&_article]:rounded-3xl [&_article]:border [&_article]:border-white/[.06] [&_article]:bg-white/[.02] [&_article]:p-6 [&_article_span]:text-[9px] [&_article_span]:font-semibold [&_article_span]:uppercase [&_article_span]:tracking-[.12em] [&_article_span]:text-cyan-300 [&_article_h3]:mt-4 [&_article_h3]:text-xl [&_article_h3]:font-semibold [&_article_p]:text-sm [&_article_p]:leading-7 [&_article_p]:text-white/45 [&_ul]:m-0 [&_ul]:mt-4 [&_ul]:grid [&_ul]:list-none [&_ul]:gap-2 [&_ul]:p-0 [&_li]:grid [&_li]:gap-1 [&_li]:rounded-2xl [&_li]:border [&_li]:border-white/[.05] [&_li]:p-3 [&_a]:text-sm [&_a]:font-medium [&_a]:text-white/75 [&_small]:text-[10px] [&_small]:text-white/35",
  simpleLanguage:
    "flex flex-wrap items-center gap-5 rounded-3xl border border-white/[.06] bg-white/[.02] p-4 pl-5 [&>div:first-child]:mr-auto [&>div:first-child]:grid [&>div:first-child]:gap-1 [&>div:first-child_span]:text-[9px] [&>div:first-child_span]:font-semibold [&>div:first-child_span]:uppercase [&>div:first-child_span]:tracking-[.12em] [&>div:first-child_span]:text-violet-300 [&>div:first-child_strong]:max-w-2xl [&>div:first-child_strong]:text-xs [&>div:first-child_strong]:font-normal [&>div:first-child_strong]:leading-5 [&>div:first-child_strong]:text-white/40 [&>div:last-child]:flex [&>div:last-child]:gap-1 [&_button]:rounded-full [&_button]:border [&_button]:border-transparent [&_button]:px-4 [&_button]:py-2.5 [&_button]:text-xs [&_button]:text-white/45 [&_button[data-active=true]]:border-violet-400/20 [&_button[data-active=true]]:bg-violet-400/[.1] [&_button[data-active=true]]:text-violet-200",
  spokenSummary:
    "flex flex-wrap items-center gap-5 rounded-3xl border border-cyan-300/15 bg-cyan-300/[.035] p-5 [&>div]:mr-auto [&>div]:grid [&>div]:gap-1 [&_span]:text-[9px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[.12em] [&_span]:text-cyan-300 [&_strong]:text-xs [&_strong]:font-normal [&_strong]:text-white/40 [&_button]:rounded-full [&_button]:border-0 [&_button]:bg-white [&_button]:px-5 [&_button]:py-3 [&_button]:text-xs [&_button]:font-semibold [&_button]:text-black [&_small]:text-xs [&_small]:text-white/40",
  checkCard:
    "grid gap-6 overflow-hidden rounded-3xl border border-violet-300/15 [background:radial-gradient(circle_at_0%_0%,rgba(139,92,246,.16),transparent_28rem),#070708] p-[clamp(1.5rem,4vw,3.5rem)] lg:grid-cols-[.65fr_1.35fr] [&>div]:self-center [&>div>span]:text-[10px] [&>div>span]:font-semibold [&>div>span]:uppercase [&>div>span]:tracking-[.14em] [&>div>span]:text-violet-300 [&>div>h2]:mt-4 [&>div>h2]:text-3xl [&>div>h2]:font-semibold [&>div>p]:text-sm [&>div>p]:leading-7 [&>div>p]:text-white/45 [&_button]:rounded-full [&_button]:border-0 [&_button]:bg-white [&_button]:px-5 [&_button]:py-3 [&_button]:text-xs [&_button]:font-semibold [&_button]:text-black [&_button:disabled]:opacity-50 [&>article]:rounded-[2rem] [&>article]:border [&>article]:border-white/10 [&>article]:bg-black/40 [&>article]:p-[clamp(1.5rem,4vw,3rem)] [&_article_header]:flex [&_article_header]:items-center [&_article_header]:justify-between [&_article_header_span]:rounded-full [&_article_header_span]:bg-violet-400/10 [&_article_header_span]:px-3 [&_article_header_span]:py-1.5 [&_article_header_span]:text-[10px] [&_article_header_span]:font-semibold [&_article_header_span]:uppercase [&_article_header_span]:tracking-[.1em] [&_article_header_span]:text-violet-200 [&_dl]:grid [&_dl]:gap-3 [&_dl_div]:rounded-2xl [&_dl_div]:border [&_dl_div]:border-white/[.06] [&_dl_div]:p-4 [&_dt]:text-[9px] [&_dt]:font-semibold [&_dt]:uppercase [&_dt]:tracking-[.12em] [&_dt]:text-cyan-300 [&_dd]:m-0 [&_dd]:mt-2 [&_dd]:text-sm [&_dd]:leading-6 [&_dd]:text-white/65 [&_footer]:text-[10px] [&_footer]:text-white/35",
  reportHeader:
    "relative grid grid-cols-[minmax(0,1.2fr)_minmax(18rem,0.45fr)] gap-[clamp(2rem,6vw,6rem)] overflow-hidden rounded-3xl border border-white/[0.06] [background:radial-gradient(circle_at_12%_0%,rgba(139,92,246,0.22),transparent_30rem),radial-gradient(circle_at_92%_8%,rgba(6,182,212,0.1),transparent_22rem),#070708] p-[clamp(2rem,6vw,5rem)] shadow-[0_30px_60px_-15px_rgba(0,0,0,0.5),0_0_0_1px_rgba(255,255,255,0.02)] max-[800px]:grid-cols-1 [&>div>span]:font-sans [&>div>span]:text-[10px] [&>div>span]:font-semibold [&>div>span]:uppercase [&>div>span]:tracking-[0.18em] [&>div>span]:text-violet-400 [&_h2]:my-5 [&_h2]:max-w-[15ch] [&_h2]:font-sans [&_h2]:text-[clamp(2.5rem,5vw,4.75rem)] [&_h2]:leading-[1.02] [&_h2]:font-semibold [&_h2]:tracking-tighter [&_p]:max-w-2xl [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/50 [&_dl]:m-0 [&_dl]:grid [&_dl]:content-start [&_dl]:gap-2 [&_dl_div]:grid [&_dl_div]:grid-cols-2 [&_dl_div]:gap-4 [&_dl_div]:rounded-2xl [&_dl_div]:border [&_dl_div]:border-white/[0.04] [&_dl_div]:bg-white/[0.025] [&_dl_div]:px-4 [&_dl_div]:py-3 [&_dt]:font-sans [&_dt]:text-[10px] [&_dt]:font-semibold [&_dt]:uppercase [&_dt]:tracking-[0.12em] [&_dt]:text-white/35 [&_dd]:m-0 [&_dd]:break-all [&_dd]:text-right [&_dd]:font-mono [&_dd]:text-[11px] [&_dd]:text-white/70",
  findings:
    "grid grid-cols-2 gap-6 max-[700px]:grid-cols-1 [&>div]:relative [&>div]:overflow-hidden [&>div]:rounded-3xl [&>div]:border [&>div]:border-white/[0.06] [&>div]:bg-card/60 [&>div]:p-[clamp(2rem,5vw,4rem)] [&>div]:shadow-[0_30px_60px_-15px_rgba(0,0,0,0.5)] [&>div]:transition-all [&>div]:duration-300 [&>div:hover]:-translate-y-0.5 [&>div:hover]:border-white/15 [&_span]:font-sans [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[0.14em] [&_span]:text-cyan-300 [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/50 [&_ol]:mb-0 [&_ol]:pl-5 [&_li]:py-2 [&_li]:text-sm [&_li]:leading-relaxed [&_li]:text-white/60",
  sourceWarning:
    "grid gap-6 rounded-3xl border border-amber-300/20 bg-amber-300/[.045] p-[clamp(1.5rem,4vw,3rem)] md:grid-cols-[.35fr_1fr] [&>span]:text-[10px] [&>span]:font-semibold [&>span]:uppercase [&>span]:tracking-[.14em] [&>span]:text-amber-200 [&_h2]:m-0 [&_h2]:text-2xl [&_h2]:font-semibold [&_h2]:tracking-tight [&_p]:mb-0 [&_p]:max-w-3xl [&_p]:text-sm [&_p]:leading-7 [&_p]:text-white/50",
  coach:
    "grid gap-8 overflow-hidden rounded-3xl border border-cyan-300/15 [background:radial-gradient(circle_at_0%_0%,rgba(6,182,212,.12),transparent_25rem),#070708] p-[clamp(1.5rem,4vw,3rem)] lg:grid-cols-[.65fr_1.35fr] [&>div>span]:text-[10px] [&>div>span]:font-semibold [&>div>span]:uppercase [&>div>span]:tracking-[.14em] [&>div>span]:text-cyan-300 [&_h2]:mt-4 [&_h2]:text-[clamp(2rem,4vw,3.5rem)] [&_h2]:font-semibold [&_h2]:leading-[1.06] [&_h2]:tracking-tight [&_p]:text-sm [&_p]:leading-7 [&_p]:text-white/50 [&>button]:self-start [&>button]:justify-self-start [&>button]:rounded-full [&>button]:border [&>button]:border-white/10 [&>button]:bg-white/[.05] [&>button]:px-4 [&>button]:py-2.5 [&>button]:text-xs",
  coachBody:
    "grid gap-3 sm:grid-cols-2 [&_article]:rounded-2xl [&_article]:border [&_article]:border-white/[.05] [&_article]:bg-white/[.02] [&_article]:p-5 [&_article_span]:text-[9px] [&_article_span]:font-semibold [&_article_span]:uppercase [&_article_span]:tracking-[.12em] [&_article_span]:text-violet-300 [&_article_p]:mb-0",
  coachLinks:
    "flex flex-wrap gap-2 sm:col-span-2 [&_a]:rounded-full [&_a]:bg-white [&_a]:px-4 [&_a]:py-2.5 [&_a]:text-xs [&_a]:font-semibold [&_a]:text-black [&_span]:rounded-full [&_span]:border [&_span]:border-white/10 [&_span]:px-4 [&_span]:py-2.5 [&_span]:text-xs [&_span]:text-white/35",
  learningRecommendations:
    "grid gap-6 rounded-3xl border border-violet-400/15 bg-violet-500/[.035] p-[clamp(1.5rem,4vw,3rem)] md:grid-cols-[.6fr_1.4fr] [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[.14em] [&_span]:text-violet-300 [&_h2]:mt-4 [&_h2]:text-3xl [&_h2]:font-semibold [&_h2]:tracking-tight [&_p]:text-sm [&_p]:leading-7 [&_p]:text-white/45 [&_ul]:m-0 [&_ul]:grid [&_ul]:list-none [&_ul]:gap-3 [&_ul]:p-0 [&_li]:rounded-2xl [&_li]:border [&_li]:border-white/[.06] [&_li]:bg-black/20 [&_li]:p-5 [&_li_h3]:mt-3 [&_li_h3]:mb-1 [&_li_h3]:text-lg [&_li_a]:mt-3 [&_li_a]:inline-flex [&_li_a]:rounded-full [&_li_a]:bg-white [&_li_a]:px-4 [&_li_a]:py-2 [&_li_a]:text-xs [&_li_a]:font-semibold [&_li_a]:text-black [&>button]:self-start [&>button]:justify-self-start [&>button]:rounded-full [&>button]:border [&>button]:border-white/10 [&>button]:bg-white/[.05] [&>button]:px-4 [&>button]:py-2.5 [&>button]:text-xs",
  claimWorkspace:
    "grid grid-cols-[minmax(0,1.2fr)_minmax(19rem,0.55fr)] gap-6 max-[900px]:grid-cols-1",
  claims:
    "min-w-0 overflow-hidden rounded-3xl border border-white/[0.06] bg-card/60 p-3 shadow-[0_30px_60px_-15px_rgba(0,0,0,0.5),0_0_0_1px_rgba(255,255,255,0.02)]",
  sectionHeading:
    "sectionHeading flex items-center justify-between gap-4 rounded-2xl border border-white/[0.04] bg-white/[0.025] px-4 py-3 font-sans text-[10px] font-semibold uppercase tracking-[0.14em] text-white/35 [&>span:last-child]:rounded-full [&>span:last-child]:border [&>span:last-child]:border-violet-400/15 [&>span:last-child]:bg-violet-400/[0.05] [&>span:last-child]:px-2.5 [&>span:last-child]:py-1 [&>span:last-child]:text-violet-300",
  claim:
    "mt-3 rounded-3xl border border-white/[0.045] bg-white/[0.018] p-[clamp(1.5rem,4vw,3rem)] transition-colors hover:bg-white/[0.028] [&>header]:flex [&>header]:items-center [&>header]:justify-between [&>header]:gap-4 [&>header_span]:font-sans [&>header_span]:text-[10px] [&>header_span]:font-semibold [&>header_span]:uppercase [&>header_span]:tracking-[0.12em] [&>header_span]:text-white/35 [&>header_span[data-verdict]]:rounded-full [&>header_span[data-verdict]]:border [&>header_span[data-verdict]]:border-white/10 [&>header_span[data-verdict]]:bg-white/[0.04] [&>header_span[data-verdict]]:px-2.5 [&>header_span[data-verdict]]:py-1 [&>header_span[data-verdict=SUPPORTED]]:border-emerald-400/20 [&>header_span[data-verdict=SUPPORTED]]:bg-emerald-400/[0.06] [&>header_span[data-verdict=SUPPORTED]]:text-emerald-400 [&>header_span[data-verdict=CONTRADICTED]]:border-danger/20 [&>header_span[data-verdict=CONTRADICTED]]:bg-danger/[0.06] [&>header_span[data-verdict=CONTRADICTED]]:text-red-300 [&>header_span[data-verdict=MIXED]]:border-amber-400/20 [&>header_span[data-verdict=MIXED]]:bg-amber-400/[0.06] [&>header_span[data-verdict=MIXED]]:text-amber-300 [&_h3]:mt-5 [&_h3]:font-sans [&_h3]:text-[clamp(1.65rem,3vw,2.75rem)] [&_h3]:font-semibold [&_h3]:leading-[1.12] [&_h3]:tracking-tighter [&>p]:text-sm [&>p]:leading-relaxed [&>p]:text-white/50",
  claimMeta:
    "flex flex-wrap gap-2 font-sans text-[10px] font-semibold uppercase tracking-[0.1em] text-white/35 [&>span]:rounded-full [&>span]:border [&>span]:border-white/[0.05] [&>span]:bg-white/[0.025] [&>span]:px-2.5 [&>span]:py-1.5",
  claimDetails:
    "mt-5 rounded-2xl border border-white/[.05] bg-black/15 p-4 [&_summary]:cursor-pointer [&_summary]:text-xs [&_summary]:font-medium [&_summary]:text-white/45 [&[open]_summary]:mb-4",
  evidenceGroup:
    "mt-7 grid gap-2 [&>span]:mb-1 [&>span]:block [&>span]:font-sans [&>span]:text-[10px] [&>span]:font-semibold [&>span]:uppercase [&>span]:tracking-[0.14em] [&>span]:text-white/35 [&_button]:grid [&_button]:w-full [&_button]:gap-1 [&_button]:rounded-2xl [&_button]:border [&_button]:border-white/[0.04] [&_button]:bg-black/20 [&_button]:p-4 [&_button]:text-left [&_button]:transition-all [&_button]:duration-200 [&_button:hover]:border-cyan-400/25 [&_button:hover]:bg-cyan-400/[0.035] [&_button:focus-visible]:outline-none [&_button:focus-visible]:ring-2 [&_button:focus-visible]:ring-violet-400/50 [&_strong]:font-sans [&_strong]:text-sm [&_strong]:font-medium [&_strong]:text-white/75 [&_small]:font-sans [&_small]:text-[11px] [&_small]:text-white/35",
  claimCaveats:
    "mt-7 rounded-2xl border border-amber-400/15 bg-amber-400/[0.045] p-4 [&>span]:font-sans [&>span]:text-[10px] [&>span]:font-semibold [&>span]:uppercase [&>span]:tracking-[0.12em] [&>span]:text-amber-300 [&_ul]:mb-0 [&_ul]:pl-5 [&_li]:py-1 [&_li]:text-xs [&_li]:leading-relaxed [&_li]:text-white/50",
  inspector:
    "sticky top-24 min-h-[30rem] self-start overflow-hidden rounded-3xl border border-cyan-400/15 [background:radial-gradient(circle_at_100%_0%,rgba(6,182,212,0.14),transparent_22rem),radial-gradient(circle_at_0%_100%,rgba(139,92,246,0.1),transparent_24rem),#070708] p-[clamp(1.5rem,4vw,3rem)] shadow-[0_30px_60px_-15px_rgba(0,0,0,0.55)] max-[900px]:static",
  inspectorLabel:
    "flex items-center justify-between gap-4 font-mono text-[10px] text-white/35 [&>span:last-child]:rounded-full [&>span:last-child]:border [&>span:last-child]:border-cyan-400/20 [&>span:last-child]:bg-cyan-400/[0.06] [&>span:last-child]:px-2.5 [&>span:last-child]:py-1 [&>span:last-child]:font-sans [&>span:last-child]:font-semibold [&>span:last-child]:uppercase [&>span:last-child]:tracking-[0.1em] [&>span:last-child]:text-cyan-300 [&>span[data-relationship=SUPPORTING]]:border-emerald-400/20 [&>span[data-relationship=SUPPORTING]]:bg-emerald-400/[0.06] [&>span[data-relationship=SUPPORTING]]:text-emerald-400 [&>span[data-relationship=CONTRADICTING]]:border-danger/20 [&>span[data-relationship=CONTRADICTING]]:bg-danger/[0.06] [&>span[data-relationship=CONTRADICTING]]:text-red-300",
  noSelection:
    "flex min-h-[22rem] flex-col justify-center [&>span]:font-sans [&>span]:text-[10px] [&>span]:font-semibold [&>span]:uppercase [&>span]:tracking-[0.14em] [&>span]:text-cyan-300 [&_h3]:mt-4 [&_h3]:font-sans [&_h3]:text-[clamp(2rem,4vw,3.25rem)] [&_h3]:font-semibold [&_h3]:leading-[1.08] [&_h3]:tracking-tighter [&_p]:max-w-md [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/50",
  evidenceDetail:
    "[&_h3]:mt-5 [&_h3]:font-sans [&_h3]:text-[clamp(1.8rem,4vw,3.25rem)] [&_h3]:font-semibold [&_h3]:leading-[1.08] [&_h3]:tracking-tighter [&_dl]:m-0 [&_dl]:grid [&_dl]:gap-2 [&_dl_div]:grid [&_dl_div]:grid-cols-2 [&_dl_div]:gap-4 [&_dl_div]:rounded-2xl [&_dl_div]:border [&_dl_div]:border-white/[0.04] [&_dl_div]:bg-white/[0.025] [&_dl_div]:px-4 [&_dl_div]:py-3 [&_dt]:font-sans [&_dt]:text-[10px] [&_dt]:font-semibold [&_dt]:uppercase [&_dt]:tracking-[0.1em] [&_dt]:text-white/35 [&_dd]:m-0 [&_dd]:text-right [&_dd]:font-sans [&_dd]:text-xs [&_dd]:text-white/70 [&_blockquote]:mx-0 [&_blockquote]:my-7 [&_blockquote]:rounded-2xl [&_blockquote]:border [&_blockquote]:border-violet-400/15 [&_blockquote]:bg-violet-400/[0.045] [&_blockquote]:p-5 [&_blockquote]:text-sm [&_blockquote]:leading-relaxed [&_blockquote]:text-white/65 [&>a]:inline-flex [&>a]:items-center [&>a]:gap-3 [&>a]:rounded-full [&>a]:border [&>a]:border-white/10 [&>a]:bg-white/[0.04] [&>a]:px-5 [&>a]:py-3 [&>a]:font-sans [&>a]:text-xs [&>a]:font-medium [&>a]:text-white/70 [&>a]:transition-colors [&>a:hover]:border-cyan-400/30 [&>a:hover]:text-cyan-300",
  unavailable: "text-sm leading-relaxed text-white/40",
  analysisGrid:
    "grid grid-cols-2 gap-6 max-[850px]:grid-cols-1",
  analysisSection:
    "overflow-hidden rounded-3xl border border-white/[0.06] bg-card/60 p-3 shadow-[0_30px_60px_-15px_rgba(0,0,0,0.5)] [&>article]:mt-3 [&>article]:rounded-2xl [&>article]:border [&>article]:border-white/[0.04] [&>article]:bg-white/[0.018] [&>article]:p-[clamp(1.25rem,3vw,2.25rem)] [&_article_header]:flex [&_article_header]:items-start [&_article_header]:justify-between [&_article_header]:gap-4 [&_article_header_span]:rounded-full [&_article_header_span]:border [&_article_header_span]:border-white/[0.05] [&_article_header_span]:bg-white/[0.025] [&_article_header_span]:px-2.5 [&_article_header_span]:py-1 [&_article_header_span]:font-sans [&_article_header_span]:text-[9px] [&_article_header_span]:font-semibold [&_article_header_span]:uppercase [&_article_header_span]:tracking-[0.1em] [&_article_header_span]:text-white/35 [&_article_header_strong]:font-sans [&_article_header_strong]:text-xl [&_article_header_strong]:font-semibold [&_article_header_strong]:tracking-tight [&_article_p]:text-sm [&_article_p]:leading-relaxed [&_article_p]:text-white/50 [&_article_blockquote]:mx-0 [&_article_blockquote]:rounded-2xl [&_article_blockquote]:border [&_article_blockquote]:border-violet-400/15 [&_article_blockquote]:bg-violet-400/[0.04] [&_article_blockquote]:p-4 [&_article_blockquote]:text-sm [&_article_blockquote]:leading-relaxed [&_article_blockquote]:text-white/65 [&_dl]:grid [&_dl]:gap-2 [&_dl_div]:rounded-2xl [&_dl_div]:border [&_dl_div]:border-white/[0.04] [&_dl_div]:bg-black/20 [&_dl_div]:px-4 [&_dl_div]:py-3 [&_dt]:font-sans [&_dt]:text-[10px] [&_dt]:font-semibold [&_dt]:uppercase [&_dt]:tracking-[0.1em] [&_dt]:text-white/35 [&_dd]:m-0 [&_dd]:mt-2 [&_dd]:text-sm [&_dd]:leading-relaxed [&_dd]:text-white/60 [&_small]:text-xs [&_small]:leading-relaxed [&_small]:text-white/35",
  score:
    "mt-5 h-2 overflow-hidden rounded-full bg-black/40 [&>span]:block [&>span]:h-full [&>span]:rounded-full [&>span]:bg-gradient-to-r [&>span]:from-[#C084FC] [&>span]:to-[#06B6D4] [&>span]:shadow-[0_0_16px_rgba(139,92,246,0.45)]",
  emptySection:
    "m-3 rounded-2xl border border-dashed border-white/[0.08] bg-white/[0.015] p-[clamp(2rem,4vw,4rem)] text-center text-sm leading-relaxed text-white/40",
  media:
    "grid grid-cols-1 gap-3 rounded-3xl border border-white/[0.06] bg-card/60 p-3 shadow-[0_30px_60px_-15px_rgba(0,0,0,0.5)] md:grid-cols-2 xl:grid-cols-3 [&>.sectionHeading]:col-span-full [&_article]:rounded-2xl [&_article]:border [&_article]:border-white/[0.04] [&_article]:bg-white/[0.018] [&_article]:p-[clamp(1.5rem,4vw,3rem)] [&_article>span]:font-sans [&_article>span]:text-[10px] [&_article>span]:font-semibold [&_article>span]:uppercase [&_article>span]:tracking-[0.14em] [&_article>span]:text-cyan-300 [&_h3]:font-sans [&_h3]:text-2xl [&_h3]:font-semibold [&_h3]:tracking-tight [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/50 [&_article_div]:grid [&_article_div]:grid-cols-2 [&_article_div]:gap-4 [&_article_div]:rounded-2xl [&_article_div]:border [&_article_div]:border-white/[0.04] [&_article_div]:bg-black/20 [&_article_div]:p-4 [&_article_strong]:text-right [&_article_strong]:font-medium [&_article_strong]:text-white/75 [&_ol]:mt-4 [&_ol]:grid [&_ol]:list-none [&_ol]:gap-2 [&_ol]:p-0 [&_li]:rounded-xl [&_li]:border [&_li]:border-white/[0.04] [&_li]:bg-black/20 [&_li]:p-3 [&_li]:text-xs [&_li]:leading-6 [&_li]:text-white/50 [&_li_strong]:text-cyan-300",
  limitations:
    "grid gap-[clamp(2rem,5vw,5rem)] rounded-3xl border border-amber-400/15 [background:radial-gradient(circle_at_0%_0%,rgba(245,158,11,0.1),transparent_26rem),#070708] p-[clamp(2rem,6vw,5rem)] text-foreground shadow-[0_30px_60px_-15px_rgba(0,0,0,0.5)] md:grid-cols-[0.8fr_1.2fr] [&_span]:font-sans [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[0.14em] [&_span]:text-amber-300 [&_h2]:mt-4 [&_h2]:text-[clamp(2.2rem,5vw,4.5rem)] [&_h2]:font-semibold [&_h2]:leading-[1.05] [&_h2]:tracking-tighter [&_ol]:m-0 [&_ol]:pl-5 [&_li]:py-2 [&_li]:text-sm [&_li]:leading-relaxed [&_li]:text-white/50 [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/50",
  reportLoading:
    "rounded-3xl border border-white/[0.06] bg-card/60 p-[clamp(2rem,6vw,5rem)] shadow-[0_30px_60px_-15px_rgba(0,0,0,0.5)] [&>span]:font-sans [&>span]:text-[10px] [&>span]:font-semibold [&>span]:uppercase [&>span]:tracking-[0.14em] [&>span]:text-violet-400 [&_h2]:mt-4 [&_h2]:font-sans [&_h2]:text-[clamp(2.5rem,5vw,4.75rem)] [&_h2]:font-semibold [&_h2]:tracking-tighter [&_div]:mt-3 [&_div]:h-20 [&_div]:animate-pulse [&_div]:rounded-2xl [&_div]:bg-white/[0.05]",
  reportError:
    "rounded-3xl border border-danger/20 bg-card/60 p-[clamp(2rem,6vw,5rem)] shadow-[0_30px_60px_-15px_rgba(0,0,0,0.5)] [&>span]:font-sans [&>span]:text-[10px] [&>span]:font-semibold [&>span]:uppercase [&>span]:tracking-[0.14em] [&>span]:text-red-300 [&_h2]:mt-4 [&_h2]:font-sans [&_h2]:text-[clamp(2.5rem,5vw,4.75rem)] [&_h2]:font-semibold [&_h2]:tracking-tighter [&_p]:max-w-2xl [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/50 [&_button]:rounded-full [&_button]:border-0 [&_button]:bg-gradient-to-r [&_button]:from-[#C084FC] [&_button]:to-[#6366F1] [&_button]:px-5 [&_button]:py-3 [&_button]:font-sans [&_button]:text-xs [&_button]:font-medium [&_button]:text-white [&_button]:transition-transform [&_button:hover]:scale-[1.02] [&_button:active]:scale-[0.98]",
  reportVersions:
    "mb-6 flex flex-wrap items-center gap-3 rounded-3xl border border-white/[0.06] bg-card/60 p-3 shadow-[0_20px_50px_-22px_rgba(0,0,0,0.65)] [&>span]:mr-auto [&>span]:px-2 [&>span]:font-sans [&>span]:text-[10px] [&>span]:font-semibold [&>span]:uppercase [&>span]:tracking-[0.14em] [&>span]:text-white/35 [&>div]:flex [&>div]:flex-wrap [&>div]:gap-2 [&_button]:rounded-full [&_button]:border [&_button]:border-white/10 [&_button]:bg-white/[0.04] [&_button]:px-3.5 [&_button]:py-2 [&_button]:font-sans [&_button]:text-[11px] [&_button]:font-medium [&_button]:text-white/55 [&_button]:transition-all [&_button:hover]:border-white/15 [&_button:hover]:bg-white/[0.08] [&_button[data-active=true]]:border-0 [&_button[data-active=true]]:bg-gradient-to-r [&_button[data-active=true]]:from-[#C084FC] [&_button[data-active=true]]:to-[#6366F1] [&_button[data-active=true]]:text-white [&_button[data-active=true]]:shadow-[0_10px_24px_-10px_rgba(139,92,246,0.55)] [&_small]:font-mono [&_small]:text-[10px] [&_small]:text-white/35",
} as const;
