export const reportActionStyles = {
  actionsRegion: "col-span-full",
  actions: "flex flex-wrap gap-2 [&_button]:border [&_button]:border-border-strong [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-sans [&_button]:text-[0.58rem] [&_button]:normal-case",
  notice: "m-0 mt-3 text-[0.72rem] text-success",
  backdrop: "fixed inset-0 z-100 flex items-center justify-center bg-black/70 p-4",
  dialog:
    "max-h-[90svh] w-full max-w-180 overflow-y-auto rounded-2xl border border-white/[0.08] bg-surface/60 bg-background p-[clamp(1.5rem,4vw,3rem)] [&>header]:flex [&>header]:items-center [&>header]:justify-between [&>header]:border-b [&>header]:border-border [&>header]:pb-4 [&>header_span]:font-sans [&>header_span]:text-[0.58rem] [&>header_span]:text-muted [&>header_span]:normal-case [&>header_button]:border-0 [&>header_button]:bg-transparent [&>header_button]:text-2xl [&_h2]:font-editorial [&_h2]:text-[clamp(2.5rem,5vw,4.5rem)] [&_h2]:font-normal [&>p]:leading-[1.6] [&>p]:text-muted-foreground [&_fieldset]:m-0 [&_fieldset]:border-0 [&_fieldset]:p-0 [&_fieldset_label]:flex [&_fieldset_label]:gap-3 [&_fieldset_label]:rounded-2xl [&_fieldset_label]:bg-white/[0.03] [&_fieldset_label]:p-4 [&_fieldset_label]:py-4 [&_fieldset_label>span]:grid [&_fieldset_label>span]:gap-1 [&_fieldset_strong]:text-sm [&_fieldset_small]:text-[0.68rem] [&_fieldset_small]:text-muted-foreground [&_legend]:mb-3 [&_legend]:font-sans [&_legend]:text-[0.58rem] [&_legend]:text-muted [&_legend]:normal-case [&_footer]:mt-8 [&_footer]:flex [&_footer]:flex-wrap [&_footer]:justify-end [&_footer]:gap-2 [&_footer]:border-t [&_footer]:border-border [&_footer]:pt-4 [&_footer_button]:border [&_footer_button]:border-border-strong [&_footer_button]:bg-transparent [&_footer_button]:p-3 [&_footer_button]:font-sans [&_footer_button]:text-[0.58rem] [&_footer_button]:normal-case [&_footer_button:last-child]:bg-gradient-to-r from-violet-500 to-indigo-500 [&_footer_button:last-child]:text-white",
  shareLink:
    "grid gap-2 rounded-2xl border border-white/[0.08] bg-surface/60 p-4 [&>span]:font-sans [&>span]:text-[0.58rem] [&>span]:text-muted [&>span]:normal-case [&_code]:overflow-x-auto [&_code]:bg-surface-muted [&_code]:p-3 [&_code]:text-xs [&_button]:justify-self-start [&_button]:border [&_button]:border-border-strong [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-sans [&_button]:text-[0.58rem] [&_button]:normal-case",
  danger: "!border-danger !bg-transparent !text-danger",
  exportChoices:
    "grid grid-cols-2 gap-4 max-[600px]:grid-cols-1 [&_button]:grid [&_button]:gap-2 [&_button]:border [&_button]:border-border-strong [&_button]:bg-transparent [&_button]:p-6 [&_button]:text-left [&_strong]:font-editorial [&_strong]:text-2xl [&_strong]:font-normal [&_span]:text-sm [&_span]:text-muted-foreground",
  field:
    "grid gap-2 py-3 [&>span]:font-sans [&>span]:text-[0.58rem] [&>span]:text-muted [&>span]:normal-case [&_select]:rounded-xl [&_select]:border [&_select]:border-border-strong [&_select]:bg-surface [&_select]:p-3 [&_textarea]:min-h-28 [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-border-strong [&_textarea]:bg-surface [&_textarea]:p-3 [&_small]:text-[0.68rem] [&_small]:text-muted-foreground",
  error: "text-[0.72rem] text-danger",
} as const;
