import { vectraStyles } from "@/lib/vectra-styles";

export const whatsappSettingsStyles = {
  page: `${vectraStyles.page} pb-12`,
  header: vectraStyles.pageHeader,
  status:
    `${vectraStyles.card} mt-5 flex items-center justify-between gap-8 p-[clamp(1.5rem,4vw,3rem)] max-[700px]:flex-col max-[700px]:items-start [&[data-linked=true]]:border-emerald-400/15 [&[data-linked=true]]:[background:radial-gradient(circle_at_0%_0%,rgba(16,185,129,0.12),transparent_28rem),rgba(7,7,8,0.6)] [&[data-linked=false]]:[background:radial-gradient(circle_at_0%_0%,rgba(139,92,246,0.13),transparent_28rem),rgba(7,7,8,0.6)] [&_span]:inline-flex [&_span]:items-center [&_span]:gap-2 [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[0.14em] [&_span]:text-violet-400 [&[data-linked=true]_span]:text-emerald-300 [&_h2]:mt-4 [&_h2]:mb-0 [&_h2]:max-w-[22ch] [&_h2]:text-3xl [&_h2]:font-semibold [&_h2]:tracking-tight [&_button]:shrink-0 [&_button]:rounded-full [&_button]:border-0 [&_button]:bg-gradient-to-r [&_button]:from-[#C084FC] [&_button]:to-[#6366F1] [&_button]:px-5 [&_button]:py-3 [&_button]:text-sm [&_button]:font-medium [&_button]:text-white [&_button]:transition-all [&_button:not(:disabled):hover]:scale-[1.02] [&_button:disabled]:cursor-not-allowed [&_button:disabled]:opacity-40`,
  danger:
    "!border !border-danger/35 !bg-none !bg-danger/[0.06] !text-red-300 hover:!bg-danger/10",
  code:
    "relative mt-5 overflow-hidden rounded-3xl border border-violet-300/15 [background-image:radial-gradient(circle_at_16%_0%,rgba(192,132,252,0.3),transparent_30rem),linear-gradient(135deg,rgba(109,40,217,0.8),rgba(67,56,202,0.72))] p-[clamp(1.5rem,5vw,4rem)] text-white shadow-[0_35px_85px_-35px_rgba(109,40,217,0.8)] before:pointer-events-none before:absolute before:-right-20 before:-bottom-24 before:size-80 before:rounded-full before:border before:border-white/10 [&>span]:relative [&>span]:text-[10px] [&>span]:font-semibold [&>span]:uppercase [&>span]:tracking-[0.16em] [&>span]:text-white/55 [&_strong]:relative [&_strong]:my-7 [&_strong]:block [&_strong]:font-mono [&_strong]:text-[clamp(2.7rem,8vw,6rem)] [&_strong]:leading-none [&_strong]:font-semibold [&_strong]:tracking-[0.16em] [&_p]:relative [&_p]:max-w-2xl [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/65 [&_small]:relative [&_small]:inline-flex [&_small]:rounded-full [&_small]:bg-black/15 [&_small]:px-3 [&_small]:py-1.5 [&_small]:font-mono [&_small]:text-[10px] [&_small]:tracking-wide [&_small]:text-white/55",
  explainer:
    `${vectraStyles.card} mt-5 p-[clamp(1.5rem,4vw,3rem)] [&>span]:text-[10px] [&>span]:font-semibold [&>span]:uppercase [&>span]:tracking-[0.14em] [&>span]:text-violet-400 [&_ol]:mt-6 [&_ol]:mb-0 [&_ol]:grid [&_ol]:list-none [&_ol]:gap-3 [&_ol]:p-0 [&_li]:grid [&_li]:grid-cols-[4.5rem_minmax(0,1fr)] [&_li]:items-start [&_li]:gap-4 [&_li]:rounded-2xl [&_li]:border [&_li]:border-white/[0.035] [&_li]:bg-white/[0.018] [&_li]:p-4 [&_li]:text-sm [&_li]:leading-relaxed [&_li]:text-white/50 max-[520px]:[&_li]:grid-cols-1 [&_strong]:inline-flex [&_strong]:w-fit [&_strong]:rounded-full [&_strong]:bg-violet-500/10 [&_strong]:px-3 [&_strong]:py-1.5 [&_strong]:text-[10px] [&_strong]:font-semibold [&_strong]:uppercase [&_strong]:tracking-[0.12em] [&_strong]:text-violet-300`,
  errorMessage:
    "mt-3 rounded-xl border border-danger/20 bg-danger/[0.07] px-4 py-3 text-sm text-red-200",
  error:
    `${vectraStyles.state} my-5 [&_button]:mt-3 [&_button]:rounded-full [&_button]:border-0 [&_button]:bg-gradient-to-r [&_button]:from-[#C084FC] [&_button]:to-[#6366F1] [&_button]:px-5 [&_button]:py-3 [&_button]:text-sm [&_button]:font-medium [&_button]:text-white`,
  backdrop:
    "fixed inset-0 z-100 flex items-center justify-center bg-black/75 p-4 backdrop-blur-md",
  dialog:
    "w-full max-w-160 rounded-3xl border border-white/[0.08] bg-[#0f1012] p-[clamp(1.5rem,4vw,2.5rem)] shadow-[0_35px_100px_rgba(0,0,0,0.75)] [&>span]:text-[10px] [&>span]:font-semibold [&>span]:uppercase [&>span]:tracking-[0.14em] [&>span]:text-violet-400 [&_h2]:mt-5 [&_h2]:mb-3 [&_h2]:text-3xl [&_h2]:font-semibold [&_h2]:tracking-tight [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/50 [&_footer]:mt-8 [&_footer]:flex [&_footer]:flex-wrap [&_footer]:justify-end [&_footer]:gap-2 [&_button]:rounded-full [&_button]:border-0 [&_button]:bg-gradient-to-r [&_button]:from-[#C084FC] [&_button]:to-[#6366F1] [&_button]:px-5 [&_button]:py-3 [&_button]:text-sm [&_button]:font-medium [&_button]:text-white [&_button]:transition-all [&_button:disabled]:opacity-40 [&_footer_button:first-child]:border [&_footer_button:first-child]:border-white/10 [&_footer_button:first-child]:bg-none [&_footer_button:first-child]:bg-white/[0.04] [&_footer_button:first-child]:text-white/70",
} as const;
