export const adminStyles = {
  page: "mx-auto max-w-[1500px]",
  hero:
    "grid grid-cols-[minmax(0,1.25fr)_minmax(18rem,0.5fr)] items-end gap-[clamp(2rem,7vw,7rem)] py-[clamp(3rem,6vw,6rem)] max-[900px]:grid-cols-1 [&_span]:font-sans [&_span]:text-[0.6rem] [&_span]:tracking-normal [&_span]:text-accent [&_span]:normal-case [&_h1]:mt-6 [&_h1]:mb-0 [&_h1]:max-w-[12ch] [&_h1]:text-[clamp(3rem,5.5vw,5.5rem)] [&_h1]:leading-[0.98] [&_h1]:font-semibold [&_h1]:tracking-normal [&_p]:m-0 [&_p]:leading-[1.65] [&_p]:text-muted-foreground",
  summary:
    "grid grid-cols-4 gap-4 max-[900px]:grid-cols-2 max-[560px]:grid-cols-1 [&>div]:grid [&>div]:gap-3 [&>div]:rounded-2xl [&>div]:bg-surface/70 [&>div]:p-[clamp(1rem,2.5vw,2.5rem)] [&_span]:text-xs [&_span]:text-muted [&_small]:text-xs [&_small]:text-muted [&_strong]:text-[clamp(2rem,4vw,4rem)] [&_strong]:font-semibold",
  grid: "grid grid-cols-2 gap-5 max-[900px]:grid-cols-1",
  record:
    "rounded-3xl bg-surface/70 p-[clamp(1.5rem,3vw,3rem)] [&_header]:flex [&_header]:items-center [&_header]:justify-between [&_header_span]:text-xs [&_header_span]:font-semibold [&_header_span]:text-violet-300 [&_header_small]:text-xs [&_header_small]:text-muted [&_ol]:mt-8 [&_ol]:mb-0 [&_ol]:grid [&_ol]:list-none [&_ol]:gap-3 [&_ol]:p-0 [&_li]:grid [&_li]:grid-cols-[minmax(7rem,0.75fr)_auto_minmax(12rem,1fr)] [&_li]:items-center [&_li]:gap-4 [&_li]:rounded-2xl [&_li]:bg-white/[0.03] [&_li]:p-4 max-[560px]:[&_li]:grid-cols-[1fr_auto] [&_li_span]:text-xs [&_li_span]:text-muted [&_li_small]:text-xs [&_li_small]:text-muted max-[560px]:[&_li_small]:col-span-full [&_li_em]:col-span-full [&_li_em]:text-xs [&_li_em]:not-italic [&_li_em]:text-muted [&_li_strong]:text-2xl [&_li_strong]:font-semibold",
  empty: "min-h-32 pt-8 leading-[1.6] text-muted-foreground",
  period:
    "flex items-center justify-between py-4 [&_span]:font-sans [&_span]:text-[0.58rem] [&_span]:text-muted [&_span]:normal-case [&_time]:text-[0.72rem]",
  loading:
    "mx-auto max-w-[1500px] py-24 [&_span]:font-sans [&_span]:text-[0.58rem] [&_span]:text-muted [&_span]:normal-case [&_h1]:font-editorial [&_h1]:text-[clamp(2.75rem,5vw,5rem)] [&_h1]:font-normal [&_div]:mt-px [&_div]:h-20 [&_div]:animate-pulse [&_div]:bg-surface-muted",
  error:
    "mx-auto max-w-[1500px] py-24 [&>span]:font-sans [&>span]:text-[0.58rem] [&>span]:text-muted [&>span]:normal-case [&_h1]:font-editorial [&_h1]:text-[clamp(2.75rem,5vw,5rem)] [&_h1]:font-normal [&_p]:leading-[1.65] [&_p]:text-muted-foreground [&_button]:border [&_button]:border-border-strong [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-sans [&_button]:text-[0.58rem] [&_button]:normal-case",
  listHero:
    "grid grid-cols-[minmax(0,1fr)_minmax(18rem,0.5fr)] items-end gap-8 py-[clamp(3rem,6vw,6rem)] max-[900px]:grid-cols-1 [&>span]:font-sans [&>span]:text-[0.58rem] [&>span]:text-muted [&>span]:normal-case [&_h1]:mt-5 [&_h1]:mb-0 [&_h1]:max-w-[13ch] [&_h1]:font-editorial [&_h1]:text-[clamp(3rem,6vw,6rem)] [&_h1]:leading-[0.92] [&_h1]:font-normal [&_h1]:tracking-normal [&_p]:m-0 [&_p]:leading-[1.6] [&_p]:text-muted-foreground",
  detailHero:
    "grid grid-cols-[minmax(0,1fr)_minmax(18rem,0.5fr)] items-end gap-8 py-[clamp(3rem,6vw,6rem)] max-[900px]:grid-cols-1 [&_span]:font-sans [&_span]:text-[0.58rem] [&_span]:text-muted [&_span]:normal-case [&_h1]:mt-5 [&_h1]:mb-0 [&_h1]:max-w-[13ch] [&_h1]:font-editorial [&_h1]:text-[clamp(3rem,6vw,6rem)] [&_h1]:leading-[0.92] [&_h1]:font-normal [&_h1]:tracking-normal [&_p]:m-0 [&_p]:leading-[1.6] [&_p]:text-muted-foreground [&>a]:justify-self-end [&>a]:border [&>a]:border-border-strong [&>a]:p-[0.8rem] [&>a]:font-sans [&>a]:text-[0.58rem] [&>a]:normal-case max-[900px]:[&>a]:justify-self-start",
  filters:
    "grid grid-cols-[repeat(3,minmax(0,1fr))_auto] items-end gap-4 rounded-3xl bg-surface/70 p-5 max-[900px]:grid-cols-2 max-[560px]:grid-cols-1 [&_label]:grid [&_label]:gap-2 [&_label]:text-xs [&_label]:font-medium [&_label]:text-muted [&_input]:min-h-11 [&_input]:rounded-xl [&_input]:border [&_input]:border-white/[0.08] [&_input]:bg-white/[0.035] [&_input]:p-3 [&_select]:min-h-11 [&_select]:rounded-xl [&_select]:border [&_select]:border-white/[0.08] [&_select]:bg-white/[0.035] [&_select]:p-3 [&_button]:min-h-11 [&_button]:rounded-full [&_button]:border-0 [&_button]:bg-gradient-to-r [&_button]:from-violet-500 [&_button]:to-indigo-500 [&_button]:px-5 [&_button]:text-xs [&_button]:font-semibold [&_button]:text-white",
  tableLoading: "flex min-h-64 items-center ",
  tableWrap: "max-w-full overflow-x-auto",
  table:
    "w-full min-w-245 border-separate border-spacing-y-2 [&_th]:p-4 [&_th]:text-left [&_th]:text-xs [&_th]:font-medium [&_th]:text-muted [&_td]:bg-surface/70 [&_td]:p-4 [&_td]:align-top [&_td]:text-[0.76rem] [&_td:first-child]:rounded-l-2xl [&_td:last-child]:rounded-r-2xl [&_td_strong]:block [&_td_small]:mt-1.5 [&_td_small]:block [&_td_small]:max-w-88 [&_td_small]:text-xs [&_td_small]:text-muted [&_td>span]:block [&_td>span]:text-xs [&_td_a]:font-semibold [&_td_a]:text-violet-300 [&_td_button]:min-h-10 [&_td_button]:rounded-full [&_td_button]:border-0 [&_td_button]:bg-white/[0.055] [&_td_button]:px-4 [&_td_button]:text-xs",
  inlineError:
    "flex items-center justify-between gap-4 border-b border-danger py-8 [&_span]:font-sans [&_span]:text-[0.58rem] [&_span]:text-muted [&_span]:normal-case [&_p]:mt-2 [&_p]:mb-0 [&_p]:text-muted-foreground [&_button]:border [&_button]:border-border-strong [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-sans [&_button]:text-[0.58rem] [&_button]:normal-case",
  listEmpty:
    "min-h-72 py-16 [&>span]:font-sans [&>span]:text-[0.58rem] [&>span]:text-muted [&>span]:normal-case [&_h2]:font-editorial [&_h2]:text-[clamp(2.5rem,5vw,5rem)] [&_h2]:font-normal",
  pagination:
    "flex items-center justify-between py-4 [&_span]:font-sans [&_span]:text-[0.58rem] [&_span]:text-muted [&_span]:normal-case [&_button]:border [&_button]:border-border-strong [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-sans [&_button]:text-[0.58rem] [&_button]:normal-case [&_button:disabled]:opacity-45",
  dossier:
    "m-0 grid grid-cols-3 border-t border-l border-border-strong max-[900px]:grid-cols-2 max-[560px]:grid-cols-1 [&>div]:min-h-32 [&>div]:border-r [&>div]:border-b [&>div]:border-border-strong [&>div]:p-6 [&_dt]:font-sans [&_dt]:text-[0.58rem] [&_dt]:text-muted [&_dt]:normal-case [&_dd]:mt-6 [&_dd]:mb-0 [&_dd]:font-editorial [&_dd]:text-2xl [&_dd]:wrap-anywhere",
  actionSection:
    "grid grid-cols-[minmax(15rem,0.45fr)_1fr] items-start gap-8  py-8 max-[900px]:grid-cols-1 [&_span]:font-sans [&_span]:text-[0.58rem] [&_span]:text-muted [&_span]:normal-case [&_header_p]:text-[0.72rem] [&_header_p]:leading-[1.55] [&_header_p]:text-muted-foreground [&>div]:flex [&>div]:flex-wrap [&>div]:gap-2 [&>h2]:m-0 [&>h2]:font-editorial [&>h2]:text-[clamp(1.8rem,3vw,3rem)] [&>h2]:font-normal [&>label]:grid [&>label]:gap-2 [&>label]:font-sans [&>label]:text-[0.58rem] [&>label]:normal-case [&_textarea]:min-h-28 [&_textarea]:resize-y [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-border [&_textarea]:bg-surface [&_textarea]:p-3 [&_select]:min-h-12 [&_select]:rounded-xl [&_select]:border [&_select]:border-border [&_select]:bg-surface [&_select]:p-3 [&_button]:min-h-10.5 [&_button]:border [&_button]:border-border-strong [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-sans [&_button]:text-[0.58rem] [&_button]:normal-case",
  actionRow: "col-span-full",
  providerGrid:
    "!grid grid-cols-3 max-[700px]:grid-cols-1 [&_label]:flex [&_label]:items-center [&_label]:gap-2.5 [&_label]:border [&_label]:border-border [&_label]:p-4",
  dialogBackdrop: "fixed inset-0 z-100 flex items-center justify-center bg-black/60 p-4",
  confirmDialog:
    "max-h-[calc(100svh-2rem)] w-full max-w-155 overflow-y-auto rounded-2xl border border-white/[0.08] bg-surface/60 bg-background p-[clamp(1.5rem,4vw,3rem)] [&>span]:font-sans [&>span]:text-[0.58rem] [&>span]:text-muted [&>span]:normal-case [&_h2]:font-editorial [&_h2]:text-[clamp(2.2rem,5vw,4rem)] [&_h2]:leading-[0.95] [&_h2]:font-normal [&>p]:leading-[1.6] [&>p]:text-muted-foreground [&_label]:grid [&_label]:gap-2 [&_label]:font-sans [&_label]:text-[0.58rem] [&_label]:text-muted [&_label]:normal-case [&_textarea]:min-h-32 [&_textarea]:resize-y [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-border [&_textarea]:bg-surface [&_textarea]:p-3 [&_footer]:mt-6 [&_footer]:flex [&_footer]:justify-end [&_footer]:gap-3 [&_button]:border [&_button]:border-border-strong [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-sans [&_button]:text-[0.58rem] [&_button]:normal-case [&_footer_button:last-child]:bg-gradient-to-r from-violet-500 to-indigo-500 [&_footer_button:last-child]:text-white",
  retryDialog:
    "max-h-[calc(100svh-2rem)] w-full max-w-155 overflow-y-auto rounded-2xl border border-white/[0.08] bg-surface/60 bg-background p-[clamp(1.5rem,4vw,3rem)] [&>span]:font-sans [&>span]:text-[0.58rem] [&>span]:text-muted [&>span]:normal-case [&_h2]:font-editorial [&_h2]:text-[clamp(2.2rem,5vw,4rem)] [&_h2]:leading-[0.95] [&_h2]:font-normal [&>p]:leading-[1.6] [&>p]:text-muted-foreground [&_dl]:border-t [&_dl]:border-border [&_dl_div]:flex [&_dl_div]:justify-between [&_dl_div]:border-b [&_dl_div]:border-border [&_dl_div]:py-3 [&_dt]:font-sans [&_dt]:text-[0.58rem] [&_dt]:text-muted [&_dt]:normal-case [&_dd]:m-0 [&_dd]:text-[0.72rem] [&_footer]:mt-6 [&_footer]:flex [&_footer]:justify-end [&_footer]:gap-3 [&_button]:border [&_button]:border-border-strong [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-sans [&_button]:text-[0.58rem] [&_button]:normal-case [&_footer_button:last-child]:bg-gradient-to-r from-violet-500 to-indigo-500 [&_footer_button:last-child]:text-white",
  auditLedger:
    "m-0 list-none p-0 [&>li]:border-b [&>li]:border-border-strong [&>li]:py-8 [&_header]:flex [&_header]:items-center [&_header]:justify-between [&_header_div]:grid [&_header_div]:gap-2 [&_header_span]:font-sans [&_header_span]:text-[0.58rem] [&_header_span]:text-muted [&_header_span]:normal-case [&_header_strong]:font-editorial [&_header_strong]:text-3xl [&_header_strong]:font-normal [&_time]:text-[0.68rem] [&_time]:text-muted-foreground [&_dl]:my-6 [&_dl]:grid [&_dl]:grid-cols-[0.7fr_0.7fr_1.5fr] max-[900px]:[&_dl]:grid-cols-2 max-[560px]:[&_dl]:grid-cols-1 [&_dl_div]:border-l [&_dl_div]:border-border [&_dl_div]:px-4 [&_dt]:font-sans [&_dt]:text-[0.58rem] [&_dt]:text-muted [&_dt]:normal-case [&_dd]:mt-2 [&_dd]:mb-0 [&_dd]:text-[0.72rem] [&_details]:border-t [&_details]:border-border [&_details]:pt-4 [&_summary]:cursor-pointer [&_summary]:font-sans [&_summary]:text-[0.58rem] [&_summary]:normal-case [&_pre]:max-h-80 [&_pre]:overflow-auto [&_pre]:bg-surface-muted [&_pre]:p-4 [&_pre]:text-[0.68rem]",
  dependencyRegion:
    " py-8 [&>header]:flex [&>header]:items-center [&>header]:justify-between [&_header_span]:font-sans [&_header_span]:text-[0.58rem] [&_header_span]:text-muted [&_header_span]:normal-case [&_dl]:mt-6 [&_dl]:grid [&_dl]:grid-cols-2 max-[560px]:[&_dl]:grid-cols-1 [&_dl_div]:min-h-32 [&_dl_div]:border [&_dl_div]:border-border [&_dl_div]:p-4 [&_dt]:font-sans [&_dt]:text-[0.58rem] [&_dt]:text-muted [&_dt]:normal-case [&_dd]:mt-4 [&_dd]:mb-2 [&_dd]:font-editorial [&_dd]:text-3xl",
  healthRegion:
    " py-8 [&_header]:flex [&_header]:items-center [&_header]:justify-between [&_header_span]:font-sans [&_header_span]:text-[0.58rem] [&_header_span]:text-muted [&_header_span]:normal-case [&>p]:min-h-28 [&>p]:py-8 [&>p]:text-muted-foreground [&_ol]:mt-6 [&_ol]:list-none [&_ol]:p-0 [&_li]:grid [&_li]:grid-cols-[minmax(8rem,1fr)_minmax(8rem,0.6fr)_auto_1fr_1fr] [&_li]:items-center [&_li]:gap-4  [&_li]:py-4 max-[900px]:[&_li]:grid-cols-2 max-[560px]:[&_li]:grid-cols-1 [&_li_strong]:font-editorial [&_li_strong]:text-xl [&_li_strong]:font-normal [&_li_small]:font-sans [&_li_small]:text-[0.58rem] [&_li_small]:text-muted [&_li_small]:normal-case",
  healthNotice:
    "grid grid-cols-[minmax(10rem,0.35fr)_1fr] items-start gap-8  py-8 max-[560px]:grid-cols-1 [&_span]:font-sans [&_span]:text-[0.58rem] [&_span]:text-muted [&_span]:normal-case [&_p]:m-0 [&_p]:leading-[1.6] [&_p]:text-muted-foreground",
} as const;
