import { vectraStyles } from "@/lib/vectra-styles";

const adminHeader =
  "[&_span]:inline-flex [&_span]:items-center [&_span]:gap-2 [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[0.15em] [&_span]:text-violet-400 [&_h1]:mt-4 [&_h1]:mb-0 [&_h1]:max-w-[20ch] [&_h1]:text-4xl [&_h1]:leading-[1.08] [&_h1]:font-semibold [&_h1]:tracking-tighter md:[&_h1]:text-5xl [&_p]:m-0 [&_p]:max-w-2xl [&_p]:text-base [&_p]:leading-relaxed [&_p]:text-white/60";

const adminButton =
  "[&_button]:rounded-full [&_button]:border [&_button]:border-white/[0.08] [&_button]:bg-white/[0.035] [&_button]:px-4 [&_button]:py-2.5 [&_button]:text-xs [&_button]:font-medium [&_button]:text-white/65 [&_button]:transition-all [&_button:not(:disabled):hover]:border-violet-400/20 [&_button:not(:disabled):hover]:bg-violet-500/10 [&_button:not(:disabled):hover]:text-white [&_button:disabled]:cursor-not-allowed [&_button:disabled]:opacity-35";

const dialogSurface =
  "max-h-[calc(100svh-2rem)] w-full max-w-3xl overflow-y-auto rounded-3xl border border-white/[0.08] bg-[#0f1012] p-[clamp(1.5rem,4vw,2.5rem)] shadow-[0_35px_100px_rgba(0,0,0,0.75)] [&>span]:text-[10px] [&>span]:font-semibold [&>span]:uppercase [&>span]:tracking-[0.14em] [&>span]:text-violet-400 [&_h2]:mt-5 [&_h2]:mb-3 [&_h2]:text-3xl [&_h2]:leading-tight [&_h2]:font-semibold [&_h2]:tracking-tight [&>p]:text-sm [&>p]:leading-relaxed [&>p]:text-white/50 [&_footer]:mt-8 [&_footer]:flex [&_footer]:flex-wrap [&_footer]:justify-end [&_footer]:gap-2 [&_button]:rounded-full [&_button]:border [&_button]:border-white/10 [&_button]:bg-white/[0.04] [&_button]:px-5 [&_button]:py-3 [&_button]:text-sm [&_button]:font-medium [&_button]:transition-all [&_button:disabled]:opacity-40 [&_footer_button:last-child]:border-0 [&_footer_button:last-child]:bg-gradient-to-r [&_footer_button:last-child]:from-[#C084FC] [&_footer_button:last-child]:to-[#6366F1] [&_footer_button:last-child]:text-white";

export const adminStyles = {
  page: `${vectraStyles.page} pb-12`,
  hero:
    `mb-8 grid grid-cols-[minmax(0,1.2fr)_minmax(18rem,0.55fr)] items-end gap-[clamp(2rem,7vw,6rem)] py-2 max-[900px]:grid-cols-1 ${adminHeader}`,
  summary:
    "grid grid-cols-4 gap-4 max-[900px]:grid-cols-2 max-[560px]:grid-cols-1 [&>div]:relative [&>div]:grid [&>div]:gap-2.5 [&>div]:overflow-hidden [&>div]:rounded-3xl [&>div]:border [&>div]:border-white/[0.06] [&>div]:[background:radial-gradient(circle_at_0%_0%,rgba(139,92,246,0.11),transparent_16rem),rgba(7,7,8,0.6)] [&>div]:p-[clamp(1.25rem,2.5vw,2rem)] [&>div]:shadow-[0_24px_55px_-36px_rgba(0,0,0,0.9)] [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[0.12em] [&_span]:text-white/35 [&_small]:text-xs [&_small]:leading-relaxed [&_small]:text-white/35 [&_strong]:text-3xl [&_strong]:font-semibold [&_strong]:tracking-tight",
  grid: "mt-5 grid grid-cols-2 gap-5 max-[900px]:grid-cols-1",
  record:
    `${vectraStyles.card} p-[clamp(1.25rem,3vw,2.25rem)] [&_header]:flex [&_header]:items-center [&_header]:justify-between [&_header]:gap-4 [&_header_span]:text-[10px] [&_header_span]:font-semibold [&_header_span]:uppercase [&_header_span]:tracking-[0.13em] [&_header_span]:text-violet-400 [&_header_small]:text-xs [&_header_small]:text-white/30 [&_ol]:mt-6 [&_ol]:mb-0 [&_ol]:grid [&_ol]:list-none [&_ol]:gap-2.5 [&_ol]:p-0 [&_li]:grid [&_li]:grid-cols-[minmax(7rem,0.75fr)_auto_minmax(12rem,1fr)] [&_li]:items-center [&_li]:gap-4 [&_li]:rounded-2xl [&_li]:border [&_li]:border-white/[0.035] [&_li]:bg-white/[0.018] [&_li]:p-4 [&_li]:transition-colors [&_li:hover]:bg-white/[0.035] max-[560px]:[&_li]:grid-cols-[1fr_auto] [&_li_span]:text-xs [&_li_span]:text-white/45 [&_li_small]:text-xs [&_li_small]:text-white/35 max-[560px]:[&_li_small]:col-span-full [&_li_em]:col-span-full [&_li_em]:text-xs [&_li_em]:not-italic [&_li_em]:text-amber-300/65 [&_li_strong]:text-2xl [&_li_strong]:font-semibold`,
  empty: "min-h-32 pt-8 text-sm leading-relaxed text-white/40",
  period:
    "mt-5 flex items-center justify-between gap-4 rounded-2xl border border-white/[0.04] bg-white/[0.018] px-4 py-3 [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[0.12em] [&_span]:text-white/30 [&_time]:font-mono [&_time]:text-[11px] [&_time]:text-white/45",
  loading:
    `${vectraStyles.state} mx-auto my-12 max-w-7xl [&_div]:mt-5 [&_div]:h-20 [&_div]:animate-pulse [&_div]:rounded-2xl [&_div]:bg-white/[0.035]`,
  error:
    `${vectraStyles.state} mx-auto my-12 max-w-7xl [&_button]:mt-3 [&_button]:rounded-full [&_button]:border-0 [&_button]:bg-gradient-to-r [&_button]:from-[#C084FC] [&_button]:to-[#6366F1] [&_button]:px-5 [&_button]:py-3 [&_button]:text-sm [&_button]:font-medium [&_button]:text-white`,
  listHero:
    `mb-8 grid grid-cols-[minmax(0,1fr)_minmax(18rem,0.58fr)] items-end gap-[clamp(2rem,6vw,6rem)] py-2 max-[760px]:grid-cols-1 [&>.admin-heading]:min-w-0 ${adminHeader}`,
  createButton:
    "inline-flex min-h-11 items-center justify-center gap-2 rounded-full border-0 bg-gradient-to-r from-[#C084FC] to-[#6366F1] px-5 text-sm font-semibold text-white shadow-[0_12px_32px_-16px_rgba(139,92,246,.8)] transition hover:scale-[1.02]",
  editorDialog:
    `${dialogSurface} relative max-w-5xl [&>form]:mt-7 [&>form]:grid [&>form]:grid-cols-2 [&>form]:gap-4 max-[620px]:[&>form]:grid-cols-1 [&_label]:grid [&_label]:gap-2 [&_label]:text-xs [&_label]:font-medium [&_label]:text-white/50 [&_label.full]:col-span-full [&_input]:min-h-11 [&_input]:rounded-2xl [&_input]:border [&_input]:border-white/[.07] [&_input]:bg-white/[.03] [&_input]:px-4 [&_input]:text-sm [&_input]:outline-none [&_input:focus]:border-violet-400/45 [&_select]:min-h-11 [&_select]:rounded-2xl [&_select]:border [&_select]:border-white/[.07] [&_select]:bg-[#111216] [&_select]:px-4 [&_textarea]:min-h-28 [&_textarea]:resize-y [&_textarea]:rounded-2xl [&_textarea]:border [&_textarea]:border-white/[.07] [&_textarea]:bg-white/[.03] [&_textarea]:p-4 [&_textarea]:text-sm [&_textarea]:leading-6 [&_textarea]:outline-none [&_textarea:focus]:border-violet-400/45 [&_textarea.code]:font-mono [&_textarea.code]:text-[11px] [&_textarea.tall]:min-h-72 [&_small]:text-[10px] [&_small]:leading-5 [&_small]:text-white/35 [&_.full]:col-span-full [&_.error]:text-sm [&_.error]:text-red-300`,
  dialogClose:
    "absolute top-5 right-5 grid size-10 place-items-center !rounded-full border border-white/10 bg-white/[.04] !p-0 text-white/55 hover:bg-white/[.08] hover:text-white",
  detailHero:
    `mb-8 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-8 py-2 max-[700px]:grid-cols-1 ${adminHeader} [&>a]:justify-self-end [&>a]:rounded-full [&>a]:border [&>a]:border-white/10 [&>a]:bg-white/[0.04] [&>a]:px-5 [&>a]:py-3 [&>a]:text-sm [&>a]:font-medium [&>a]:transition-colors [&>a:hover]:bg-white/[0.08] max-[700px]:[&>a]:justify-self-start`,
  filters:
    "mb-5 grid grid-cols-[repeat(3,minmax(0,1fr))_auto] items-end gap-4 rounded-3xl border border-white/[0.06] bg-card/60 p-5 shadow-[0_24px_60px_-36px_rgba(0,0,0,0.9)] max-[900px]:grid-cols-2 max-[560px]:grid-cols-1 [&_label]:grid [&_label]:gap-2 [&_label]:text-xs [&_label]:font-medium [&_label]:text-white/45 [&_input]:min-h-11 [&_input]:w-full [&_input]:rounded-2xl [&_input]:border [&_input]:border-white/[0.055] [&_input]:bg-white/[0.025] [&_input]:px-4 [&_input]:outline-none [&_input]:transition-all [&_input:focus]:border-violet-400/40 [&_input:focus]:bg-white/[0.045] [&_select]:min-h-11 [&_select]:w-full [&_select]:rounded-2xl [&_select]:border [&_select]:border-white/[0.055] [&_select]:bg-white/[0.025] [&_select]:px-4 [&_select]:outline-none [&_select:focus]:border-violet-400/40 [&_button]:min-h-11 [&_button]:rounded-full [&_button]:border-0 [&_button]:bg-gradient-to-r [&_button]:from-[#C084FC] [&_button]:to-[#6366F1] [&_button]:px-5 [&_button]:text-sm [&_button]:font-medium [&_button]:text-white [&_button]:transition-all [&_button:not(:disabled):hover]:scale-[1.02]",
  tableLoading:
    "flex min-h-56 items-center rounded-3xl border border-white/[0.06] bg-card/60 p-8 text-sm text-white/40 shadow-[0_24px_60px_-36px_rgba(0,0,0,0.9)]",
  tableWrap:
    "max-w-full overflow-x-auto rounded-3xl border border-white/[0.06] bg-card/60 p-2 shadow-[0_24px_60px_-36px_rgba(0,0,0,0.9)]",
  table:
    "w-full min-w-245 border-separate border-spacing-y-2 [&_th]:px-4 [&_th]:py-2.5 [&_th]:text-left [&_th]:text-[10px] [&_th]:font-semibold [&_th]:uppercase [&_th]:tracking-[0.12em] [&_th]:text-white/30 [&_td]:border-y [&_td]:border-white/[0.035] [&_td]:bg-white/[0.018] [&_td]:p-4 [&_td]:align-top [&_td]:text-xs [&_td]:text-white/60 [&_tbody_tr:hover_td]:border-white/[0.07] [&_tbody_tr:hover_td]:bg-white/[0.035] [&_td:first-child]:rounded-l-2xl [&_td:first-child]:border-l [&_td:last-child]:rounded-r-2xl [&_td:last-child]:border-r [&_td_strong]:block [&_td_strong]:text-sm [&_td_strong]:font-semibold [&_td_strong]:text-white/85 [&_td_small]:mt-1.5 [&_td_small]:block [&_td_small]:max-w-88 [&_td_small]:text-[11px] [&_td_small]:leading-relaxed [&_td_small]:text-white/30 [&_td>span]:inline-flex [&_td>span]:rounded-full [&_td>span]:bg-white/[0.04] [&_td>span]:px-2.5 [&_td>span]:py-1 [&_td>span]:text-[10px] [&_td>span]:font-medium [&_td>span]:text-white/55 [&_td_a]:inline-flex [&_td_a]:rounded-full [&_td_a]:bg-violet-500/10 [&_td_a]:px-3.5 [&_td_a]:py-2 [&_td_a]:font-medium [&_td_a]:text-violet-300 [&_td_button]:min-h-9 [&_td_button]:rounded-full [&_td_button]:border-0 [&_td_button]:bg-white/[0.05] [&_td_button]:px-4 [&_td_button]:text-xs",
  inlineError:
    `mb-5 flex items-center justify-between gap-5 rounded-3xl border border-danger/20 bg-danger/[0.065] p-5 [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[0.12em] [&_span]:text-red-300 [&_p]:mt-2 [&_p]:mb-0 [&_p]:text-sm [&_p]:text-red-100/60 ${adminButton}`,
  listEmpty:
    `${vectraStyles.state} min-h-64 [&_h2]:max-w-[22ch]`,
  pagination:
    `mt-5 flex items-center justify-between gap-4 rounded-2xl border border-white/[0.04] bg-white/[0.018] p-3 [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[0.12em] [&_span]:text-white/30 ${adminButton} [&_button:disabled]:opacity-30`,
  dossier:
    "m-0 grid grid-cols-3 gap-3 max-[900px]:grid-cols-2 max-[560px]:grid-cols-1 [&>div]:min-h-32 [&>div]:rounded-3xl [&>div]:border [&>div]:border-white/[0.05] [&>div]:bg-card/60 [&>div]:p-5 [&>div]:shadow-[0_20px_50px_-38px_rgba(0,0,0,0.9)] [&_dt]:text-[10px] [&_dt]:font-semibold [&_dt]:uppercase [&_dt]:tracking-[0.12em] [&_dt]:text-white/30 [&_dd]:mt-5 [&_dd]:mb-0 [&_dd]:overflow-hidden [&_dd]:font-mono [&_dd]:text-xs [&_dd]:leading-relaxed [&_dd]:text-white/65 [&_dd]:wrap-anywhere",
  actionSection:
    `${vectraStyles.card} mt-5 grid grid-cols-[minmax(13rem,0.42fr)_minmax(0,1fr)] items-start gap-6 p-[clamp(1.5rem,4vw,2.5rem)] max-[900px]:grid-cols-1 [&>span]:text-[10px] [&>span]:font-semibold [&>span]:uppercase [&>span]:tracking-[0.13em] [&>span]:text-violet-400 [&_header_p]:text-sm [&_header_p]:leading-relaxed [&_header_p]:text-white/45 [&>div]:flex [&>div]:flex-wrap [&>div]:gap-2 [&>h2]:m-0 [&>h2]:text-3xl [&>h2]:font-semibold [&>h2]:tracking-tight [&>label]:grid [&>label]:gap-2 [&>label]:text-xs [&>label]:font-medium [&>label]:text-white/45 [&_textarea]:min-h-28 [&_textarea]:resize-y [&_textarea]:rounded-2xl [&_textarea]:border [&_textarea]:border-white/[0.055] [&_textarea]:bg-white/[0.025] [&_textarea]:p-4 [&_textarea]:outline-none [&_textarea]:transition-all [&_textarea:focus]:border-violet-400/40 [&_select]:min-h-11 [&_select]:rounded-2xl [&_select]:border [&_select]:border-white/[0.055] [&_select]:bg-white/[0.025] [&_select]:px-4 [&_select]:outline-none ${adminButton}`,
  actionRow: "col-span-full",
  providerGrid:
    "!grid grid-cols-3 gap-3 max-[700px]:grid-cols-1 [&_label]:flex [&_label]:items-center [&_label]:gap-3 [&_label]:rounded-2xl [&_label]:border [&_label]:border-white/[0.04] [&_label]:bg-white/[0.02] [&_label]:p-4 [&_label]:transition-colors [&_label:hover]:bg-white/[0.04]",
  dialogBackdrop:
    "fixed inset-0 z-100 flex items-center justify-center bg-black/75 p-4 backdrop-blur-md",
  confirmDialog:
    `${dialogSurface} [&_label]:grid [&_label]:gap-2 [&_label]:text-xs [&_label]:font-medium [&_label]:text-white/45 [&_textarea]:min-h-32 [&_textarea]:resize-y [&_textarea]:rounded-2xl [&_textarea]:border [&_textarea]:border-white/[0.055] [&_textarea]:bg-white/[0.025] [&_textarea]:p-4 [&_textarea]:outline-none [&_textarea:focus]:border-violet-400/40`,
  retryDialog:
    `${dialogSurface} [&_dl]:m-0 [&_dl]:mt-6 [&_dl]:grid [&_dl]:gap-2 [&_dl_div]:flex [&_dl_div]:justify-between [&_dl_div]:gap-4 [&_dl_div]:rounded-2xl [&_dl_div]:border [&_dl_div]:border-white/[0.035] [&_dl_div]:bg-white/[0.018] [&_dl_div]:px-4 [&_dl_div]:py-3 [&_dt]:text-[10px] [&_dt]:font-semibold [&_dt]:uppercase [&_dt]:tracking-[0.12em] [&_dt]:text-white/30 [&_dd]:m-0 [&_dd]:font-mono [&_dd]:text-[11px] [&_dd]:text-white/60`,
  auditLedger:
    "m-0 grid list-none gap-4 p-0 [&>li]:rounded-3xl [&>li]:border [&>li]:border-white/[0.05] [&>li]:bg-card/60 [&>li]:p-[clamp(1.25rem,3vw,2rem)] [&>li]:shadow-[0_20px_50px_-38px_rgba(0,0,0,0.9)] [&_header]:flex [&_header]:items-center [&_header]:justify-between [&_header]:gap-5 [&_header_div]:grid [&_header_div]:gap-2 [&_header_span]:text-[10px] [&_header_span]:font-semibold [&_header_span]:uppercase [&_header_span]:tracking-[0.12em] [&_header_span]:text-violet-400 [&_header_strong]:text-xl [&_header_strong]:font-semibold [&_time]:font-mono [&_time]:text-[10px] [&_time]:text-white/35 [&_dl]:my-5 [&_dl]:grid [&_dl]:grid-cols-[0.7fr_0.7fr_1.5fr] [&_dl]:gap-2 max-[900px]:[&_dl]:grid-cols-2 max-[560px]:[&_dl]:grid-cols-1 [&_dl_div]:rounded-2xl [&_dl_div]:border [&_dl_div]:border-white/[0.035] [&_dl_div]:bg-white/[0.018] [&_dl_div]:p-4 [&_dt]:text-[10px] [&_dt]:font-semibold [&_dt]:uppercase [&_dt]:tracking-[0.12em] [&_dt]:text-white/30 [&_dd]:mt-2 [&_dd]:mb-0 [&_dd]:text-xs [&_dd]:text-white/60 [&_details]:rounded-2xl [&_details]:border [&_details]:border-white/[0.04] [&_details]:bg-white/[0.018] [&_details]:p-4 [&_summary]:cursor-pointer [&_summary]:text-xs [&_summary]:font-medium [&_summary]:text-violet-300 [&_pre]:max-h-80 [&_pre]:overflow-auto [&_pre]:rounded-xl [&_pre]:bg-black/25 [&_pre]:p-4 [&_pre]:font-mono [&_pre]:text-[11px] [&_pre]:text-white/55",
  dependencyRegion:
    `${vectraStyles.card} mt-5 p-[clamp(1.25rem,3vw,2rem)] [&>header]:flex [&>header]:items-center [&>header]:justify-between [&_header_span]:text-[10px] [&_header_span]:font-semibold [&_header_span]:uppercase [&_header_span]:tracking-[0.12em] [&_header_span]:text-violet-400 [&_dl]:mt-5 [&_dl]:mb-0 [&_dl]:grid [&_dl]:grid-cols-2 [&_dl]:gap-3 max-[560px]:[&_dl]:grid-cols-1 [&_dl_div]:min-h-28 [&_dl_div]:rounded-2xl [&_dl_div]:border [&_dl_div]:border-white/[0.04] [&_dl_div]:bg-white/[0.018] [&_dl_div]:p-4 [&_dt]:text-[10px] [&_dt]:font-semibold [&_dt]:uppercase [&_dt]:tracking-[0.12em] [&_dt]:text-white/30 [&_dd]:mt-4 [&_dd]:mb-2 [&_dd]:text-2xl [&_dd]:font-semibold`,
  healthRegion:
    `${vectraStyles.card} mt-5 p-[clamp(1.25rem,3vw,2rem)] [&_header]:flex [&_header]:items-center [&_header]:justify-between [&_header]:gap-4 [&_header_span]:text-[10px] [&_header_span]:font-semibold [&_header_span]:uppercase [&_header_span]:tracking-[0.12em] [&_header_span]:text-violet-400 [&>p]:min-h-24 [&>p]:py-6 [&>p]:text-sm [&>p]:text-white/45 [&_ol]:mt-5 [&_ol]:mb-0 [&_ol]:grid [&_ol]:list-none [&_ol]:gap-2.5 [&_ol]:p-0 [&_li]:grid [&_li]:grid-cols-[minmax(8rem,1fr)_minmax(8rem,0.6fr)_auto_1fr_1fr] [&_li]:items-center [&_li]:gap-4 [&_li]:rounded-2xl [&_li]:border [&_li]:border-white/[0.035] [&_li]:bg-white/[0.018] [&_li]:p-4 max-[900px]:[&_li]:grid-cols-2 max-[560px]:[&_li]:grid-cols-1 [&_li_strong]:text-base [&_li_strong]:font-semibold [&_li_small]:text-[10px] [&_li_small]:uppercase [&_li_small]:tracking-[0.1em] [&_li_small]:text-white/30`,
  healthNotice:
    "mt-5 grid grid-cols-[minmax(10rem,0.35fr)_1fr] items-start gap-8 rounded-2xl border border-cyan-400/10 bg-cyan-400/[0.035] p-5 max-[560px]:grid-cols-1 [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[0.12em] [&_span]:text-cyan-300 [&_p]:m-0 [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/45",
} as const;
