export const quizStyles = {
  page:
    "mx-auto max-w-[1100px] [&>header]:py-[clamp(3rem,7vw,7rem)] [&>header>span]:text-sm [&>header>span]:text-muted [&_h1]:my-6 [&_h1]:text-[clamp(2.5rem,5vw,4.5rem)] [&_h1]:leading-[1] [&_h1]:font-semibold [&>header>p]:max-w-180 [&>header>p]:leading-[1.6] [&>header>p]:text-muted-foreground [&_dl]:my-10 [&_dl]:grid [&_dl]:grid-cols-3 [&_dl]:gap-3 max-[600px]:[&_dl]:grid-cols-1 [&_dl_div]:flex [&_dl_div]:justify-between [&_dl_div]:rounded-2xl [&_dl_div]:bg-white/[0.04] [&_dl_div]:p-4 [&_dt]:text-sm [&_dt]:text-muted [&_dd]:m-0 [&_dd]:text-sm [&_form]:grid [&_form]:gap-4 [&_form]:rounded-3xl [&_form]:border [&_form]:border-white/[0.08] [&_form]:bg-surface/60 [&_form]:p-[clamp(1.25rem,4vw,3rem)] [&_fieldset]:m-0 [&_fieldset]:rounded-2xl [&_fieldset]:border [&_fieldset]:border-white/[0.07] [&_fieldset]:bg-white/[0.03] [&_fieldset]:p-[clamp(1.25rem,3vw,2.5rem)] [&_legend]:mb-5 [&_legend]:text-[clamp(1.4rem,3vw,2.2rem)] [&_legend]:font-semibold [&_legend_span]:mb-3 [&_legend_span]:block [&_legend_span]:text-sm [&_legend_span]:text-muted [&_fieldset>label]:mt-2 [&_fieldset>label]:flex [&_fieldset>label]:gap-4 [&_fieldset>label]:rounded-xl [&_fieldset>label]:bg-white/[0.04] [&_fieldset>label]:p-4 [&_fieldset>label]:transition-colors [&_fieldset>label:hover]:bg-white/[0.08] [&_form>button]:mt-4 [&_form>button]:w-fit [&_form>button]:rounded-xl [&_form>button]:border-0 [&_form>button]:bg-gradient-to-r [&_form>button]:from-violet-500 [&_form>button]:to-indigo-500 [&_form>button]:p-[0.9rem] [&_form>button]:text-sm [&_form>button]:text-white",
  state: "mx-auto max-w-[1100px] py-24",
  error:
    "mx-auto max-w-[1100px] py-24 [&>span]:font-sans [&>span]:text-[0.58rem] [&>span]:tracking-normal [&>span]:text-muted [&>span]:normal-case [&_h1]:my-6 [&_h1]:font-editorial [&_h1]:text-[clamp(2.75rem,5vw,5rem)] [&_h1]:leading-[0.88] [&_h1]:font-normal [&_h1]:tracking-normal [&_p]:max-w-180 [&_p]:leading-[1.6] [&_p]:text-muted-foreground [&_button]:mt-8 [&_button]:bg-gradient-to-r from-violet-500 to-indigo-500 [&_button]:p-[0.9rem] [&_button]:font-sans [&_button]:text-[0.58rem] [&_button]:text-white [&_button]:normal-case",
  explanation:
    "mt-4 border-l-2 border-danger p-4 data-[correct=true]:border-success [&_p]:leading-[1.55] [&_p]:text-muted-foreground",
  submitError: "text-danger",
  attemptError:
    "flex items-center gap-4 rounded-2xl border border-danger/30 bg-danger/5 p-4 [&_span]:text-sm [&_span]:text-muted [&_p]:flex-1 [&_p]:text-sm [&_p]:text-muted-foreground [&_button]:rounded-xl [&_button]:border [&_button]:border-border-strong [&_button]:bg-transparent [&_button]:p-3 [&_button]:text-sm",
  attemptHistory:
    "rounded-2xl border border-white/[0.08] bg-surface/60 p-4 [&>span]:text-sm [&>span]:text-muted [&_ol]:mt-4 [&_ol]:mb-0 [&_ol]:grid [&_ol]:list-none [&_ol]:gap-2 [&_ol]:p-0 [&_li]:grid [&_li]:grid-cols-[1fr_auto_minmax(5rem,auto)] [&_li]:items-center [&_li]:gap-4 [&_li]:rounded-xl [&_li]:bg-white/[0.04] [&_li]:p-3 [&_li_span]:text-sm [&_li_span]:text-muted [&_li_small]:text-xs [&_li_small]:text-muted [&_li_strong]:text-xl [&_li_strong]:font-semibold",
  result:
    "mt-12 [&>span]:font-sans [&>span]:text-[0.58rem] [&>span]:tracking-normal [&>span]:text-muted [&>span]:normal-case [&>strong]:block [&>strong]:font-editorial [&>strong]:text-8xl [&>strong]:font-normal [&_p]:leading-[1.55] [&_p]:text-muted-foreground [&_a]:mt-8 [&_a]:inline-block [&_a]:bg-gradient-to-r from-violet-500 to-indigo-500 [&_a]:p-[0.9rem] [&_a]:font-sans [&_a]:text-[0.58rem] [&_a]:text-white [&_a]:normal-case [&_button]:ml-3 [&_button]:border [&_button]:border-border-strong [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-sans [&_button]:text-[0.58rem] [&_button]:normal-case",
} as const;
