export const quizStyles = {
  page:
    "mx-auto max-w-[1100px] [&>header]:py-[clamp(3rem,7vw,7rem)] [&>header>span]:font-mono [&>header>span]:text-[0.58rem] [&>header>span]:tracking-[0.07em] [&>header>span]:text-muted [&>header>span]:uppercase [&_h1]:my-6 [&_h1]:font-editorial [&_h1]:text-[clamp(3.5rem,7vw,7rem)] [&_h1]:leading-[0.88] [&_h1]:font-normal [&_h1]:tracking-[-0.065em] [&>header>p]:max-w-180 [&>header>p]:leading-[1.6] [&>header>p]:text-muted-foreground [&_dl]:my-12 [&_dl]:grid [&_dl]:grid-cols-3 max-[600px]:[&_dl]:grid-cols-1 [&_dl_div]:flex [&_dl_div]:justify-between [&_dl_div]:border-t [&_dl_div]:border-border [&_dl_div]:p-[0.8rem] [&_dt]:font-mono [&_dt]:text-[0.58rem] [&_dt]:tracking-[0.07em] [&_dt]:text-muted [&_dt]:uppercase [&_dd]:m-0 [&_dd]:text-[0.7rem] [&_form]:border [&_form]:border-border-strong [&_form]:p-[clamp(1.5rem,4vw,4rem)] [&_fieldset]:m-0 [&_fieldset]:border-0 [&_fieldset]:border-b [&_fieldset]:border-border-strong [&_fieldset]:py-12 [&_legend]:mb-6 [&_legend]:font-editorial [&_legend]:text-[clamp(1.7rem,3vw,2.7rem)] [&_legend]:tracking-[-0.035em] [&_legend_span]:mb-3 [&_legend_span]:block [&_legend_span]:font-mono [&_legend_span]:text-[0.58rem] [&_legend_span]:tracking-[0.07em] [&_legend_span]:text-muted [&_legend_span]:uppercase [&_fieldset>label]:flex [&_fieldset>label]:gap-4 [&_fieldset>label]:border-t [&_fieldset>label]:border-border [&_fieldset>label]:py-4 [&_form>button]:mt-8 [&_form>button]:inline-block [&_form>button]:border-0 [&_form>button]:bg-foreground [&_form>button]:p-[0.9rem] [&_form>button]:font-mono [&_form>button]:text-[0.58rem] [&_form>button]:text-background [&_form>button]:uppercase",
  state: "mx-auto max-w-[1100px] py-24",
  error:
    "mx-auto max-w-[1100px] py-24 [&>span]:font-mono [&>span]:text-[0.58rem] [&>span]:tracking-[0.07em] [&>span]:text-muted [&>span]:uppercase [&_h1]:my-6 [&_h1]:font-editorial [&_h1]:text-[clamp(3.5rem,7vw,7rem)] [&_h1]:leading-[0.88] [&_h1]:font-normal [&_h1]:tracking-[-0.065em] [&_p]:max-w-180 [&_p]:leading-[1.6] [&_p]:text-muted-foreground [&_button]:mt-8 [&_button]:bg-foreground [&_button]:p-[0.9rem] [&_button]:font-mono [&_button]:text-[0.58rem] [&_button]:text-background [&_button]:uppercase",
  explanation:
    "mt-4 border-l-2 border-danger p-4 data-[correct=true]:border-success [&_p]:leading-[1.55] [&_p]:text-muted-foreground",
  submitError: "text-danger",
  attemptError:
    "flex items-center gap-4 border border-b-0 border-border-strong p-4 [&_span]:font-mono [&_span]:text-[0.58rem] [&_span]:text-muted [&_span]:uppercase [&_p]:flex-1 [&_p]:text-[0.72rem] [&_p]:text-muted-foreground [&_button]:border [&_button]:border-border-strong [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-mono [&_button]:text-[0.58rem] [&_button]:uppercase",
  attemptHistory:
    "border border-b-0 border-border-strong p-4 [&>span]:font-mono [&>span]:text-[0.58rem] [&>span]:text-muted [&>span]:uppercase [&_ol]:mt-4 [&_ol]:mb-0 [&_ol]:list-none [&_ol]:p-0 [&_li]:grid [&_li]:grid-cols-[1fr_auto_minmax(5rem,auto)] [&_li]:items-center [&_li]:gap-4 [&_li]:border-t [&_li]:border-border [&_li]:py-3 [&_li_span]:font-mono [&_li_span]:text-[0.58rem] [&_li_span]:text-muted [&_li_span]:uppercase [&_li_small]:font-mono [&_li_small]:text-[0.58rem] [&_li_small]:text-muted [&_li_small]:uppercase [&_li_strong]:font-editorial [&_li_strong]:text-2xl [&_li_strong]:font-normal",
  result:
    "mt-12 [&>span]:font-mono [&>span]:text-[0.58rem] [&>span]:tracking-[0.07em] [&>span]:text-muted [&>span]:uppercase [&>strong]:block [&>strong]:font-editorial [&>strong]:text-8xl [&>strong]:font-normal [&_p]:leading-[1.55] [&_p]:text-muted-foreground [&_a]:mt-8 [&_a]:inline-block [&_a]:bg-foreground [&_a]:p-[0.9rem] [&_a]:font-mono [&_a]:text-[0.58rem] [&_a]:text-background [&_a]:uppercase [&_button]:ml-3 [&_button]:border [&_button]:border-border-strong [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-mono [&_button]:text-[0.58rem] [&_button]:uppercase",
} as const;
