import { vectraStyles } from "@/lib/vectra-styles";

export const challengeStyles = {
  page: vectraStyles.pageMedium,
  workspace:
    `${vectraStyles.pageMedium} [&>header]:mb-6 [&>header]:rounded-3xl [&>header]:border [&>header]:border-white/[0.06] [&>header]:bg-card/60 [&>header]:p-[clamp(1.5rem,4vw,3rem)] [&>header]:shadow-[0_30px_60px_-15px_rgba(0,0,0,0.5)] [&>header>span]:inline-flex [&>header>span]:rounded-full [&>header>span]:border [&>header>span]:border-violet-400/20 [&>header>span]:bg-violet-400/[0.06] [&>header>span]:px-3 [&>header>span]:py-1.5 [&>header>span]:text-xs [&>header>span]:font-medium [&>header>span]:text-violet-300 [&>header>h1]:mt-5 [&>header>h1]:mb-0 [&>header>h1]:max-w-[18ch] [&>header>h1]:text-[clamp(2.35rem,5vw,4.5rem)] [&>header>h1]:leading-[1.04] [&>header>h1]:font-semibold [&>header>h1]:tracking-tighter [&>header>p]:mt-4 [&>header>p]:max-w-3xl [&>header>p]:text-sm [&>header>p]:leading-relaxed [&>header>p]:text-white/50 [&>header>dl]:mt-7 [&>header>dl]:mb-0 [&>header>dl]:grid [&>header>dl]:gap-3 [&>header>dl]:md:grid-cols-3 [&>header>dl_div]:rounded-2xl [&>header>dl_div]:border [&>header>dl_div]:border-white/[0.04] [&>header>dl_div]:bg-white/[0.02] [&>header>dl_div]:p-4 [&>header>dl_dt]:text-[11px] [&>header>dl_dt]:text-white/35 [&>header>dl_dd]:mt-2 [&>header>dl_dd]:ml-0 [&>header>dl_dd]:text-sm [&>header>dl_dd]:font-medium [&>header>dl_dd]:text-white/75`,
  header: vectraStyles.pageHeader,
  loading:
    `${vectraStyles.card} grid gap-3 p-6 [&>span]:text-xs [&>span]:font-medium [&>span]:text-white/45 [&_div]:h-24 [&_div]:animate-pulse [&_div]:rounded-2xl [&_div]:bg-white/[0.05]`,
  error:
    `${vectraStyles.state} min-h-80 [&_button]:mt-5 [&_button]:rounded-full [&_button]:border [&_button]:border-white/10 [&_button]:bg-white/[0.04] [&_button]:px-5 [&_button]:py-3 [&_button]:text-sm [&_button]:font-medium [&_button:hover]:bg-white/[0.08]`,
  empty: `${vectraStyles.state} min-h-80`,
  workspaceState:
    `${vectraStyles.state} flex min-h-80 items-center justify-center text-sm text-white/50`,
  list:
    "m-0 grid list-none gap-4 p-0 [&_li]:overflow-hidden [&_li]:rounded-3xl [&_li]:border [&_li]:border-white/[0.06] [&_li]:bg-card/60 [&_li]:shadow-[0_24px_60px_-24px_rgba(0,0,0,0.55)] [&_li]:transition-all [&_li]:duration-300 [&_li[data-completed=true]]:border-emerald-400/15 [&_li:hover]:border-white/15 [&_li:hover]:bg-white/[0.025] [&_a]:grid [&_a]:grid-cols-[2.25rem_minmax(0,1fr)_minmax(14rem,0.48fr)_auto] [&_a]:items-center [&_a]:gap-6 [&_a]:p-[clamp(1.35rem,3vw,2.25rem)] max-[750px]:[&_a]:grid-cols-[2.25rem_minmax(0,1fr)_auto] max-[750px]:[&_dl]:hidden [&_a>span]:grid [&_a>span]:size-9 [&_a>span]:place-items-center [&_a>span]:rounded-xl [&_a>span]:bg-violet-500/10 [&_a>span]:text-xs [&_a>span]:font-semibold [&_a>span]:text-violet-300 [&_small]:text-[11px] [&_small]:font-medium [&_small]:text-white/35 [&_h2]:my-2.5 [&_h2]:text-[clamp(1.35rem,2.5vw,2rem)] [&_h2]:font-semibold [&_h2]:tracking-tight [&_p]:m-0 [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/50 [&_dl]:m-0 [&_dl]:grid [&_dl]:gap-2 [&_dl_div]:grid [&_dl_div]:grid-cols-[1fr_auto] [&_dl_div]:gap-4 [&_dl_div]:rounded-xl [&_dl_div]:border [&_dl_div]:border-white/[0.04] [&_dl_div]:bg-white/[0.02] [&_dl_div]:px-3 [&_dl_div]:py-2.5 [&_dt]:text-[11px] [&_dt]:text-white/35 [&_dd]:m-0 [&_dd]:text-right [&_dd]:text-[11px] [&_dd]:font-medium [&_a>strong]:grid [&_a>strong]:size-9 [&_a>strong]:place-items-center [&_a>strong]:rounded-full [&_a>strong]:bg-white/[0.04] [&_a>strong]:text-sm [&_a>strong]:text-white/45 [&_a>strong]:transition-all [&_a:hover>strong]:bg-violet-500/15 [&_a:hover>strong]:text-violet-300",
  completedBadge:
    "mt-3 inline-flex w-fit items-center rounded-full border border-emerald-300/20 bg-emerald-400/10 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.08em] text-emerald-300",
  context:
    `${vectraStyles.card} mb-6 grid gap-7 [background-image:radial-gradient(circle_at_top_left,rgba(139,92,246,0.18),transparent_58%)] p-[clamp(1.5rem,4vw,3rem)] md:grid-cols-[0.35fr_1fr] [&>span]:inline-flex [&>span]:h-fit [&>span]:w-fit [&>span]:rounded-full [&>span]:border [&>span]:border-violet-400/20 [&>span]:bg-violet-400/[0.06] [&>span]:px-3 [&>span]:py-1.5 [&>span]:text-xs [&>span]:font-medium [&>span]:text-violet-300 [&_p]:m-0 [&_p]:text-[15px] [&_p]:leading-relaxed [&_p]:text-white/65`,
  questions:
    `${vectraStyles.card} grid gap-4 p-[clamp(1.25rem,4vw,2.5rem)] [&_fieldset]:m-0 [&_fieldset]:min-w-0 [&_fieldset]:rounded-2xl [&_fieldset]:border [&_fieldset]:border-white/[0.05] [&_fieldset]:bg-white/[0.02] [&_fieldset]:p-[clamp(1.25rem,3vw,2rem)] [&_legend]:mb-5 [&_legend]:max-w-3xl [&_legend]:text-[clamp(1.2rem,2.5vw,1.65rem)] [&_legend]:leading-snug [&_legend]:font-semibold [&_legend_span]:mb-3 [&_legend_span]:block [&_legend_span]:text-[11px] [&_legend_span]:font-medium [&_legend_span]:text-violet-300 [&_fieldset>label]:mt-2 [&_fieldset>label]:flex [&_fieldset>label]:cursor-pointer [&_fieldset>label]:items-center [&_fieldset>label]:gap-3.5 [&_fieldset>label]:rounded-2xl [&_fieldset>label]:border [&_fieldset>label]:border-white/[0.04] [&_fieldset>label]:bg-white/[0.025] [&_fieldset>label]:p-4 [&_fieldset>label]:text-sm [&_fieldset>label]:text-white/65 [&_fieldset>label]:transition-all [&_fieldset>label:hover]:border-white/10 [&_fieldset>label:hover]:bg-white/[0.05] [&_fieldset>label:focus-within]:border-violet-400/35 [&_fieldset>label:has(input:checked)]:border-violet-400/30 [&_fieldset>label:has(input:checked)]:bg-violet-500/10 [&_fieldset_input]:size-4 [&_fieldset_input]:accent-violet-500`,
  explanation:
    "mt-4 rounded-2xl border border-red-400/20 bg-red-400/[0.05] p-4 data-[correct=true]:border-emerald-400/20 data-[correct=true]:bg-emerald-400/[0.05] [&_strong]:text-sm [&_strong]:font-semibold [&_p]:mt-2 [&_p]:mb-0 [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/55",
  submit:
    `${vectraStyles.primaryAction} mt-2 inline-flex min-h-11 items-center justify-center disabled:cursor-not-allowed`,
  submitError:
    "rounded-2xl border border-red-400/20 bg-red-400/[0.05] p-4 text-sm text-red-200",
  result:
    "mt-4 rounded-3xl border border-emerald-400/20 bg-emerald-400/[0.05] p-[clamp(1.5rem,4vw,3rem)] [&>span]:text-xs [&>span]:font-medium [&>span]:text-emerald-300 [&>strong]:mt-4 [&>strong]:block [&>strong]:text-[clamp(4rem,10vw,7rem)] [&>strong]:leading-none [&>strong]:font-semibold [&_p]:max-w-xl [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/55 [&_a]:mt-6 [&_a]:inline-flex [&_a]:rounded-full [&_a]:bg-gradient-to-r [&_a]:from-[#C084FC] [&_a]:to-[#6366F1] [&_a]:px-5 [&_a]:py-3 [&_a]:text-sm [&_a]:font-medium [&_a]:text-white [&_a]:transition-all [&_a:hover]:scale-[1.02]",
} as const;
