export const missionWorkspaceStyles = {
  page: "mx-auto grid max-w-[1500px] gap-6 pb-16",
  hero: "grid gap-[clamp(2rem,6vw,6rem)] rounded-[2rem] border border-white/[.06] [background:radial-gradient(circle_at_10%_0%,rgba(6,182,212,.14),transparent_30rem),radial-gradient(circle_at_90%_100%,rgba(139,92,246,.16),transparent_28rem),#070708] p-[clamp(2rem,6vw,5rem)] lg:grid-cols-[1.15fr_.85fr] [&_span]:text-[10px] [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[.14em] [&_span]:text-cyan-300 [&_h1]:mt-4 [&_h1]:text-[clamp(3rem,7vw,6rem)] [&_h1]:font-semibold [&_h1]:leading-[.95] [&_h1]:tracking-tight [&_p]:max-w-2xl [&_p]:text-sm [&_p]:leading-7 [&_p]:text-white/50 [&_dl]:m-0 [&_dl]:grid [&_dl]:content-center [&_dl]:gap-2 [&_dl_div]:grid [&_dl_div]:grid-cols-[.4fr_1fr] [&_dl_div]:gap-3 [&_dl_div]:rounded-2xl [&_dl_div]:border [&_dl_div]:border-white/[.05] [&_dl_div]:bg-white/[.025] [&_dl_div]:p-4 [&_dt]:text-[9px] [&_dt]:uppercase [&_dt]:text-white/30 [&_dd]:m-0 [&_dd]:text-right [&_dd]:text-xs",
  join: "flex flex-wrap items-center gap-6 rounded-3xl border border-violet-400/15 bg-violet-400/[.04] p-[clamp(1.5rem,4vw,3rem)] [&>div]:mr-auto [&_span]:text-[9px] [&_span]:uppercase [&_span]:tracking-[.14em] [&_span]:text-violet-300 [&_h2]:mt-3 [&_h2]:text-3xl [&_p]:max-w-3xl [&_p]:text-sm [&_p]:text-white/45 [&_button]:rounded-full [&_button]:border-0 [&_button]:bg-white [&_button]:px-5 [&_button]:py-3 [&_button]:text-xs [&_button]:font-semibold [&_button]:text-black",
  assessment: "grid gap-4 rounded-[2rem] border border-violet-400/15 bg-card/60 p-[clamp(1.5rem,4vw,3rem)] [&>header_span]:text-[9px] [&>header_span]:uppercase [&>header_span]:tracking-[.14em] [&>header_span]:text-violet-300 [&>header_h2]:mt-3 [&>header_h2]:text-3xl [&>header_p]:text-sm [&>header_p]:text-white/45 [&_fieldset]:grid [&_fieldset]:gap-2 [&_fieldset]:rounded-3xl [&_fieldset]:border [&_fieldset]:border-white/[.06] [&_fieldset]:p-5 [&_legend]:grid [&_legend]:gap-2 [&_legend]:px-1 [&_legend]:text-base [&_legend_small]:text-[9px] [&_legend_small]:uppercase [&_legend_small]:tracking-[.12em] [&_legend_small]:text-cyan-300 [&_label]:flex [&_label]:gap-3 [&_label]:rounded-2xl [&_label]:border [&_label]:border-white/[.05] [&_label]:p-4 [&_label:has(input:checked)]:border-violet-400/30 [&_label:has(input:checked)]:bg-violet-400/[.06] [&_input]:accent-violet-400 [&>button]:justify-self-start [&>button]:rounded-full [&>button]:border-0 [&>button]:bg-white [&>button]:px-5 [&>button]:py-3 [&>button]:text-xs [&>button]:font-semibold [&>button]:text-black [&>button:disabled]:opacity-40",
  scenarios: "rounded-[2rem] border border-white/[.06] bg-card/60 p-[clamp(1.5rem,4vw,3rem)] [&>header_span]:text-[9px] [&>header_span]:uppercase [&>header_span]:tracking-[.14em] [&>header_span]:text-cyan-300 [&>header_h2]:mt-3 [&>header_h2]:text-3xl [&>header_p]:text-sm [&>header_p]:text-white/45 [&>div]:mt-6 [&>div]:grid [&>div]:gap-3 md:[&>div]:grid-cols-2 [&_article]:rounded-3xl [&_article]:border [&_article]:border-white/[.06] [&_article]:bg-black/20 [&_article]:p-6 [&_article_span]:text-[9px] [&_article_span]:uppercase [&_article_span]:text-violet-300 [&_article_h3]:mt-3 [&_article_h3]:text-2xl [&_article_p]:text-sm [&_article_p]:leading-7 [&_article_p]:text-white/50 [&_article_small]:text-[9px] [&_article_small]:text-cyan-200/50 [&_textarea]:mt-5 [&_textarea]:min-h-28 [&_textarea]:w-full [&_textarea]:rounded-2xl [&_textarea]:border [&_textarea]:border-white/10 [&_textarea]:bg-black/30 [&_textarea]:p-4 [&_textarea]:text-sm [&_article_button]:mt-3 [&_article_button]:rounded-full [&_article_button]:border [&_article_button]:border-white/10 [&_article_button]:px-4 [&_article_button]:py-2.5 [&_article_button]:text-xs",
  learning: "rounded-[2rem] border border-cyan-300/15 bg-cyan-300/[.035] p-[clamp(1.5rem,4vw,3rem)] [&>header_span]:text-[9px] [&>header_span]:uppercase [&>header_span]:tracking-[.14em] [&>header_span]:text-cyan-300 [&>header_h2]:mt-3 [&>header_h2]:text-3xl [&>header_p]:text-sm [&>header_p]:text-white/45 [&>div]:mt-6 [&>div]:grid [&>div]:gap-3 md:[&>div]:grid-cols-2 [&_article]:rounded-3xl [&_article]:border [&_article]:border-white/[.06] [&_article]:bg-black/20 [&_article]:p-6 [&_article_span]:text-[9px] [&_article_span]:uppercase [&_article_span]:text-emerald-300 [&_article_h3]:mt-3 [&_article_h3]:text-2xl [&_article_p]:text-sm [&_article_p]:leading-7 [&_article_p]:text-white/50 [&_article_a]:mt-3 [&_article_a]:inline-flex [&_article_a]:rounded-full [&_article_a]:bg-white [&_article_a]:px-4 [&_article_a]:py-2.5 [&_article_a]:text-xs [&_article_a]:font-semibold [&_article_a]:text-black",
  impact: "grid gap-6 rounded-[2rem] border border-emerald-300/15 bg-emerald-300/[.035] p-[clamp(2rem,5vw,4rem)] md:grid-cols-[1fr_auto] [&_span]:text-[9px] [&_span]:uppercase [&_span]:tracking-[.14em] [&_span]:text-emerald-300 [&_h2]:mt-4 [&_h2]:text-4xl [&_p]:max-w-3xl [&_p]:text-sm [&_p]:text-white/45 [&_dl]:m-0 [&_dl]:flex [&_dl]:gap-3 [&_dl_div]:rounded-2xl [&_dl_div]:bg-black/20 [&_dl_div]:p-4 [&_dt]:text-[9px] [&_dt]:uppercase [&_dt]:text-white/30 [&_dd]:m-0 [&_dd]:mt-2 [&_dd]:text-xl [&_a]:justify-self-start [&_a]:rounded-full [&_a]:bg-white [&_a]:px-5 [&_a]:py-3 [&_a]:text-xs [&_a]:font-semibold [&_a]:text-black",
  state: "rounded-[2rem] border border-white/[.06] bg-card/60 p-[clamp(2rem,5vw,4rem)] [&_span]:text-[9px] [&_span]:uppercase [&_span]:text-violet-300 [&_h1]:text-4xl [&_p]:text-white/50 [&_button]:rounded-full [&_button]:border [&_button]:border-white/10 [&_button]:px-4 [&_button]:py-2.5",
  back: "justify-self-start rounded-full border border-white/10 px-5 py-3 text-xs text-white/60",
} as const;
