"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import Link from "next/link";
import { useState } from "react";
import { missionService } from "@/services/missions";
import type { MissionAssessment } from "@/types/missions";
import { missionWorkspaceStyles as styles } from "./mission.styles";

function AssessmentForm({ assessment, slug, onComplete }: { assessment: MissionAssessment; slug: string; onComplete: () => void }) {
  const [answers, setAnswers] = useState<Record<string, string[]>>({});
  const submit = useMutation({ mutationFn: () => missionService.submitAssessment(slug, assessment.phase, assessment.questions.map((question) => ({ questionId: question.id, selectedOptionIds: answers[question.id] ?? [] }))), onSuccess: onComplete });
  return <form className={styles.assessment} onSubmit={(event) => { event.preventDefault(); submit.mutate(); }}><header><span>{assessment.phase.replaceAll("_", " ")} assessment</span><h2>{assessment.phase === "BASELINE" ? "Start with what you know today." : "See what changed after practice."}</h2><p>Correct answers are scored on the server and are never included in this question payload. This assessment allows {assessment.maxAttempts} attempt.</p></header>{assessment.questions.map((question, index) => <fieldset key={question.id}><legend><small>{String(index + 1).padStart(2, "0")} · {question.competency.replaceAll("_", " ")}</small>{question.prompt}</legend>{question.options.map((option) => { const multiple = question.type === "MULTIPLE_CHOICE"; const checked = answers[question.id]?.includes(option.id) ?? false; return <label key={option.id}><input checked={checked} name={question.id} type={multiple ? "checkbox" : "radio"} onChange={() => setAnswers((current) => { const existing = current[question.id] ?? []; return { ...current, [question.id]: multiple ? checked ? existing.filter((id) => id !== option.id) : [...existing, option.id] : [option.id] }; })} /><span>{option.text}</span></label>; })}</fieldset>)}{submit.error && <p role="alert">{submit.error.message}</p>}<button disabled={submit.isPending || assessment.questions.some((question) => !(answers[question.id]?.length))} type="submit">{submit.isPending ? "Scoring securely…" : `Submit ${assessment.phase === "BASELINE" ? "baseline" : "follow-up"}`}</button></form>;
}

export default function MissionWorkspace({ slug }: { slug: string }) {
  const queryClient = useQueryClient();
  const [reflection, setReflection] = useState<Record<string, string>>({});
  const mission = useQuery({ queryKey: ["mission", slug], queryFn: () => missionService.get(slug) });
  const participation = mission.data?.participation;
  const linkedLearningComplete = Boolean(mission.data) && (!mission.data!.learning.required || [...mission.data!.learning.lessons, ...mission.data!.learning.challenges].every((item) => item.completed));
  const phase: "BASELINE" | "FOLLOW_UP" | null = participation && participation.baselineScore === null ? "BASELINE" : participation && participation.completedScenarioIds.length >= (mission.data?.scenarios.length ?? Infinity) && linkedLearningComplete && participation.followUpScore === null ? "FOLLOW_UP" : null;
  const assessment = useQuery({ enabled: Boolean(phase), queryKey: ["mission-assessment", slug, phase], queryFn: () => missionService.assessment(slug, phase!) });
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: ["mission", slug] }); void queryClient.invalidateQueries({ queryKey: ["mission-assessment", slug] }); };
  const join = useMutation({ mutationFn: () => missionService.join(slug, true), onSuccess: refresh });
  const scenario = useMutation({ mutationFn: ({ scenarioId }: { scenarioId: string }) => missionService.completeScenario(slug, scenarioId, reflection[scenarioId] ?? ""), onSuccess: refresh });
  const impact = useQuery({ enabled: participation?.status === "COMPLETED", queryKey: ["mission-impact", slug], queryFn: () => missionService.impact(slug) });
  if (mission.isPending) return <section className={styles.state} aria-busy="true"><span>Community mission</span><h1>Opening the mission…</h1></section>;
  if (mission.isError) return <section className={styles.state} role="alert"><span>Mission unavailable</span><h1>This mission could not be opened.</h1><p>{mission.error.message}</p><button onClick={() => void mission.refetch()} type="button">Retry</button></section>;
  const record = mission.data;
  return <div className={styles.page}>
    <header className={styles.hero}><div><span>{record.difficulty} · {record.topic}</span><h1>{record.title}</h1><p>{record.summary}</p></div><dl><div><dt>Audience</dt><dd>{record.audience}</dd></div><div><dt>Facilitator</dt><dd>{record.organization}</dd></div><div><dt>Your status</dt><dd>{participation?.status.replaceAll("_", " ") ?? "Not joined"}</dd></div></dl></header>
    {!participation ? <section className={styles.join}><div><span>Before you join</span><h2>Practise safely with synthetic scenarios.</h2><p>{record.privacyPolicy}</p></div><button disabled={join.isPending} onClick={() => join.mutate()} type="button">{join.isPending ? "Joining…" : "Consent and join mission"}</button></section> : null}
    {participation && phase === "BASELINE" && (assessment.isPending ? <section className={styles.state}><h2>Preparing your baseline…</h2></section> : assessment.data ? <AssessmentForm assessment={assessment.data} slug={slug} onComplete={refresh} /> : null)}
    {participation?.baselineScore !== null && participation && participation.followUpScore === null && <section className={styles.scenarios}><header><span>Mission scenarios</span><h2>Apply the check before the follow-up.</h2><p>Every scenario is synthetic and created for safe media-literacy practice. Your reflection is private.</p></header><div>{record.scenarios.map((item, index) => { const complete = participation.completedScenarioIds.includes(item.id); return <article key={item.id}><span>{String(index + 1).padStart(2, "0")} · {complete ? "Completed" : "Practice scenario"}</span><h3>{item.title}</h3><p>{item.description}</p><small>{item.competencies.join(" · ").replaceAll("_", " ")}</small>{!complete && <><textarea placeholder="What would you check, and what would you tell the sender?" value={reflection[item.id] ?? ""} onChange={(event) => setReflection((current) => ({ ...current, [item.id]: event.target.value }))} /><button disabled={!reflection[item.id]?.trim() || scenario.isPending} onClick={() => scenario.mutate({ scenarioId: item.id })} type="button">Save reflection</button></>}</article>; })}</div></section>}
    {participation?.baselineScore !== null && participation && participation.followUpScore === null && record.learning.required && <section className={styles.learning}><header><span>Linked learning</span><h2>Build the skill, then demonstrate it.</h2><p>The follow-up opens after the mission’s real lesson and practice challenge are complete.</p></header><div>{record.learning.lessons.map((item) => <article key={item.id}><span>{item.completed ? "Completed" : `${item.estimatedDuration} min lesson`}</span><h3>{item.title}</h3><p>{item.summary}</p><Link href={`/app/lessons/${item.slug}`}>{item.completed ? "Review lesson" : "Open lesson"}</Link></article>)}{record.learning.challenges.map((item) => <article key={item.id}><span>{item.completed ? "Completed" : `${item.difficulty} challenge`}</span><h3>{item.title}</h3><p>{item.scenario}</p><Link href={`/app/challenges/${item.slug}`}>{item.completed ? "Review challenge" : "Start challenge"}</Link></article>)}</div></section>}
    {participation && phase === "FOLLOW_UP" && (assessment.isPending ? <section className={styles.state}><h2>Preparing your follow-up…</h2></section> : assessment.data ? <AssessmentForm assessment={assessment.data} slug={slug} onComplete={refresh} /> : null)}
    {participation?.status === "COMPLETED" && <section className={styles.impact}><div><span>Your mission impact</span><h2>{impact.data?.change === null || impact.data?.change === undefined ? "Assessment comparison pending" : `${impact.data.change >= 0 ? "+" : ""}${impact.data.change.toFixed(1)} percentage points`}</h2><p>{impact.data?.limitation}</p></div><dl><div><dt>Baseline</dt><dd>{impact.data?.baselineScore ?? "—"}%</dd></div><div><dt>Follow-up</dt><dd>{impact.data?.followUpScore ?? "—"}%</dd></div></dl><Link href="/app/growth">Open growth profile</Link></section>}
    <Link className={styles.back} href="/app/leaderboards">Return to community</Link>
  </div>;
}
