export const learningStyles = {
  catalog: "mx-auto max-w-[1400px]",
  course: "mx-auto max-w-[1400px]",
  hero:
    "grid grid-cols-[minmax(0,1.2fr)_minmax(18rem,0.55fr)] gap-[clamp(2rem,7vw,7rem)] py-[clamp(3rem,6vw,6rem)] max-[800px]:grid-cols-1 [&>span]:col-span-full [&>span]:font-mono [&>span]:text-[0.6rem] [&>span]:tracking-[0.16em] [&>span]:text-accent [&>span]:uppercase max-[800px]:[&>span]:col-span-1 [&_h1]:m-0 [&_h1]:text-[clamp(3rem,6vw,6rem)] [&_h1]:leading-[0.98] [&_h1]:font-semibold [&_h1]:tracking-[-0.055em] [&_p]:m-0 [&_p]:self-end [&_p]:leading-[1.65] [&_p]:text-muted-foreground",
  courseHeader:
    "grid grid-cols-[minmax(0,1.2fr)_minmax(18rem,0.55fr)] gap-[clamp(2rem,7vw,7rem)] py-[clamp(3rem,7vw,7rem)] max-[800px]:grid-cols-1 [&_span]:font-mono [&_span]:text-[0.58rem] [&_span]:tracking-[0.075em] [&_span]:text-muted [&_span]:uppercase [&_h1]:m-0 [&_h1]:font-editorial [&_h1]:text-[clamp(3.5rem,7vw,7.5rem)] [&_h1]:leading-[0.88] [&_h1]:font-normal [&_h1]:tracking-[-0.065em] [&_p]:m-0 [&_p]:self-end [&_p]:leading-[1.65] [&_p]:text-muted-foreground [&_dl]:m-0 [&_dl_div]:grid [&_dl_div]:grid-cols-2 [&_dl_div]:gap-4 [&_dl_div]:border-t [&_dl_div]:border-border [&_dl_div]:py-3 [&_dd]:m-0 [&_dd]:text-right [&_dd]:text-[0.7rem] [&_dd]:capitalize",
  loading:
    "[&>span]:font-mono [&>span]:text-[0.58rem] [&>span]:tracking-[0.075em] [&>span]:text-muted [&>span]:uppercase [&_div]:mt-px [&_div]:h-22.5 [&_div]:animate-pulse [&_div]:bg-surface-muted",
  error:
    "flex min-h-90 flex-col items-start justify-center [&>span]:font-mono [&>span]:text-[0.58rem] [&>span]:tracking-[0.075em] [&>span]:text-muted [&>span]:uppercase [&_h2]:font-editorial [&_h2]:text-[clamp(2.3rem,4vw,4rem)] [&_h2]:font-normal [&_h2]:tracking-[-0.045em] [&_p]:text-muted-foreground [&_button]:border [&_button]:border-border [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-mono [&_button]:text-[0.58rem] [&_button]:uppercase",
  empty:
    "flex min-h-90 flex-col items-start justify-center [&>span]:font-mono [&>span]:text-[0.58rem] [&>span]:tracking-[0.075em] [&>span]:text-muted [&>span]:uppercase [&_h2]:font-editorial [&_h2]:text-[clamp(2.3rem,4vw,4rem)] [&_h2]:font-normal [&_h2]:tracking-[-0.045em] [&_p]:text-muted-foreground",
  courseLoading:
    "flex min-h-90 flex-col items-start justify-center [&>span]:font-mono [&>span]:text-[0.58rem] [&>span]:tracking-[0.075em] [&>span]:text-muted [&>span]:uppercase [&_h1]:font-editorial [&_h1]:text-[clamp(3.5rem,7vw,7.5rem)] [&_h1]:leading-[0.88] [&_h1]:font-normal [&_h1]:tracking-[-0.065em]",
  courseList:
    "m-0 list-none overflow-hidden rounded-2xl border border-white/[0.08] bg-[#050505] p-0 [&_li]:border-b [&_li]:border-white/[0.07] [&_a]:grid [&_a]:grid-cols-[2rem_minmax(0,1fr)_minmax(14rem,0.45fr)_auto] [&_a]:items-start [&_a]:gap-8 [&_a]:px-5 [&_a]:py-[clamp(1.5rem,3vw,3rem)] [&_a]:transition-colors [&_a:hover]:bg-white/[0.025] max-[800px]:[&_a]:grid-cols-[2rem_1fr_auto] [&_span]:font-mono [&_span]:text-[0.58rem] [&_span]:tracking-[0.075em] [&_span]:text-accent [&_span]:uppercase [&_small]:font-mono [&_small]:text-[0.58rem] [&_small]:tracking-[0.075em] [&_small]:text-muted [&_small]:uppercase [&_h2]:my-2.5 [&_h2]:text-[clamp(1.8rem,3vw,3rem)] [&_h2]:font-medium [&_h2]:tracking-[-0.045em] [&_p]:m-0 [&_p]:leading-[1.55] [&_p]:text-muted-foreground [&_dl]:m-0 max-[800px]:[&_dl]:hidden [&_dl_div]:grid [&_dl_div]:grid-cols-2 [&_dl_div]:gap-4 [&_dl_div]:border-t [&_dl_div]:border-border [&_dl_div]:py-3 [&_dt]:font-mono [&_dt]:text-[0.58rem] [&_dt]:tracking-[0.075em] [&_dt]:text-muted [&_dt]:uppercase [&_dd]:m-0 [&_dd]:text-right [&_dd]:text-[0.7rem] [&_dd]:capitalize",
  objectives:
    "grid grid-cols-[0.4fr_1fr] gap-12 bg-foreground p-[clamp(2rem,5vw,5rem)] text-background max-[800px]:grid-cols-1 [&>span]:font-mono [&>span]:text-[0.58rem] [&>span]:tracking-[0.075em] [&>span]:text-muted [&>span]:uppercase [&_ol]:m-0 [&_ol]:pl-5 [&_li]:border-t [&_li]:border-[color-mix(in_srgb,var(--background)_22%,transparent)] [&_li]:py-4 [&_li]:leading-[1.55] [&_li]:text-[color-mix(in_srgb,var(--background)_78%,transparent)]",
  progressError:
    "flex items-center justify-between gap-8 border border-b-0 border-warning p-4 [&_span]:font-mono [&_span]:text-[0.58rem] [&_span]:text-warning [&_span]:uppercase [&_p]:mt-1.5 [&_p]:text-[0.72rem] [&_p]:text-muted-foreground [&_button]:border [&_button]:border-border [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-mono [&_button]:text-[0.58rem] [&_button]:uppercase",
  readerGrid:
    "grid grid-cols-[minmax(16rem,0.45fr)_minmax(0,1.3fr)] items-start border border-t-0 border-border-strong max-[800px]:grid-cols-1 [&_aside]:sticky [&_aside]:top-17.5 [&_aside]:border-r [&_aside]:border-border-strong [&_aside]:bg-surface [&_aside]:p-8 max-[800px]:[&_aside]:static max-[800px]:[&_aside]:border-r-0 max-[800px]:[&_aside]:border-b [&_aside>span]:font-mono [&_aside>span]:text-[0.58rem] [&_aside>span]:tracking-[0.075em] [&_aside>span]:text-muted [&_aside>span]:uppercase [&_aside>ol]:my-6 [&_aside>ol]:list-none [&_aside>ol]:p-0 [&_aside_button]:grid [&_aside_button]:w-full [&_aside_button]:grid-cols-[2rem_1fr_auto] [&_aside_button]:items-start [&_aside_button]:gap-3 [&_aside_button]:border-0 [&_aside_button]:border-t [&_aside_button]:border-border [&_aside_button]:bg-transparent [&_aside_button]:py-4 [&_aside_button]:text-left [&_aside_button[data-active=true]_strong]:text-accent [&_aside_button_span]:font-mono [&_aside_button_span]:text-[0.56rem] [&_aside_button_span]:text-muted [&_aside_button_span]:uppercase [&_aside_small]:font-mono [&_aside_small]:text-[0.56rem] [&_aside_small]:text-muted [&_aside_small]:uppercase [&_aside_button_strong]:text-[0.72rem] [&_aside_button_strong]:font-medium [&_aside>a]:font-mono [&_aside>a]:text-[0.56rem] [&_aside>a]:text-muted [&_aside>a]:uppercase",
  lesson:
    "min-w-0 p-[clamp(2rem,5vw,5rem)] [&_header]:flex [&_header]:justify-between [&_header]:font-mono [&_header]:text-[0.58rem] [&_header]:tracking-[0.075em] [&_header]:text-muted [&_header]:uppercase [&_h2]:my-8 [&_h2]:mb-4 [&_h2]:font-editorial [&_h2]:text-[clamp(2.5rem,5vw,5rem)] [&_h2]:leading-[0.95] [&_h2]:font-normal [&_h2]:tracking-[-0.055em] [&_footer]:mt-16 [&_footer]:flex [&_footer]:items-center [&_footer]:justify-between [&_footer]:gap-4 [&_footer]:border-t [&_footer]:border-border-strong [&_footer]:pt-4 [&_footer>span]:font-mono [&_footer>span]:text-[0.58rem] [&_footer>span]:tracking-[0.075em] [&_footer>span]:text-muted [&_footer>span]:uppercase [&_footer_button]:border-0 [&_footer_button]:bg-foreground [&_footer_button]:p-3 [&_footer_button]:font-mono [&_footer_button]:text-[0.58rem] [&_footer_button]:text-background [&_footer_button]:uppercase [&_footer_p]:text-[0.7rem] [&_footer_p]:text-danger",
  standaloneLesson:
    "border border-border-strong [&>a]:block [&>a]:border-b [&>a]:border-border-strong [&>a]:p-4 [&>a]:font-mono [&>a]:text-[0.58rem] [&>a]:uppercase",
  lessonSummary: "text-base leading-[1.65] text-muted-foreground",
  lessonBody:
    "mt-12 border-t border-border-strong pt-8 leading-7 [&_h2]:mt-10 [&_h2]:font-editorial [&_h2]:font-normal [&_h2]:tracking-[-0.03em] [&_h3]:mt-10 [&_h3]:font-editorial [&_h3]:font-normal [&_h3]:tracking-[-0.03em] [&_h4]:mt-10 [&_h4]:font-editorial [&_h4]:font-normal [&_h4]:tracking-[-0.03em] [&_blockquote]:ml-0 [&_blockquote]:border-l-2 [&_blockquote]:border-accent [&_blockquote]:pl-6 [&_blockquote]:text-muted-foreground [&_pre]:max-w-full [&_pre]:overflow-x-auto [&_pre]:bg-surface-muted [&_pre]:p-4",
  lessonQuiz:
    "mt-8 grid grid-cols-[minmax(8rem,0.35fr)_minmax(0,1fr)_auto] items-center gap-4 border-t border-border-strong pt-8 max-[800px]:grid-cols-1 max-[800px]:items-start [&>span]:font-mono [&>span]:text-[0.58rem] [&>span]:tracking-[0.075em] [&>span]:text-muted [&>span]:uppercase [&_h3]:m-0 [&_h3]:font-editorial [&_h3]:text-[1.7rem] [&_h3]:font-normal [&_p]:mt-1.5 [&_p]:text-[0.72rem] [&_p]:text-muted-foreground [&_a]:border [&_a]:border-border-strong [&_a]:bg-transparent [&_a]:p-3 [&_a]:font-mono [&_a]:text-[0.58rem] [&_a]:uppercase [&_button]:border [&_button]:border-border-strong [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-mono [&_button]:text-[0.58rem] [&_button]:uppercase",
} as const;
