import { vectraStyles } from "@/lib/vectra-styles";

export const learningStyles = {
  catalog: vectraStyles.page,
  course: vectraStyles.page,
  hero: vectraStyles.pageHeader,
  courseHeader:
    `${vectraStyles.card} mb-6 grid gap-8 p-[clamp(1.5rem,4vw,3rem)] lg:grid-cols-[minmax(0,1.25fr)_minmax(17rem,0.55fr)] lg:items-end [&>div>span]:inline-flex [&>div>span]:items-center [&>div>span]:gap-2 [&>div>span]:text-[10px] [&>div>span]:font-semibold [&>div>span]:text-violet-400 [&>div>span]:before:size-1.5 [&>div>span]:before:rounded-full [&>div>span]:before:bg-violet-400 [&_h1]:mt-4 [&_h1]:mb-0 [&_h1]:max-w-[18ch] [&_h1]:text-[clamp(2.35rem,5vw,4.5rem)] [&_h1]:leading-[1.04] [&_h1]:font-semibold [&_h1]:tracking-tighter [&_p]:mt-4 [&_p]:mb-0 [&_p]:max-w-2xl [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/50 [&_dl]:m-0 [&_dl]:grid [&_dl]:gap-2 [&_dl_div]:grid [&_dl_div]:grid-cols-[1fr_auto] [&_dl_div]:gap-5 [&_dl_div]:rounded-2xl [&_dl_div]:border [&_dl_div]:border-white/[0.04] [&_dl_div]:bg-white/[0.02] [&_dl_div]:px-4 [&_dl_div]:py-3.5 [&_dt]:text-xs [&_dt]:text-white/40 [&_dd]:m-0 [&_dd]:text-right [&_dd]:text-xs [&_dd]:font-medium [&_dd]:capitalize [&_dd]:text-white/75`,
  loading:
    `${vectraStyles.card} grid gap-3 p-6 [&>span]:text-xs [&>span]:font-medium [&>span]:text-white/45 [&_div]:h-24 [&_div]:animate-pulse [&_div]:rounded-2xl [&_div]:bg-white/[0.05]`,
  error:
    `${vectraStyles.state} flex min-h-80 flex-col items-start justify-center [&_button]:mt-5 [&_button]:rounded-full [&_button]:border [&_button]:border-white/10 [&_button]:bg-white/[0.04] [&_button]:px-5 [&_button]:py-3 [&_button]:text-sm [&_button]:font-medium [&_button]:transition-all [&_button:hover]:border-white/15 [&_button:hover]:bg-white/[0.08]`,
  empty:
    `${vectraStyles.state} flex min-h-80 flex-col items-start justify-center`,
  courseLoading:
    `${vectraStyles.state} flex min-h-80 flex-col items-start justify-center`,
  courseList:
    "m-0 grid list-none gap-4 p-0 [&_li]:overflow-hidden [&_li]:rounded-3xl [&_li]:border [&_li]:border-white/[0.06] [&_li]:bg-card/60 [&_li]:shadow-[0_24px_60px_-24px_rgba(0,0,0,0.55)] [&_li]:transition-all [&_li]:duration-300 [&_li:hover]:border-white/15 [&_li:hover]:bg-white/[0.025] [&_a]:grid [&_a]:grid-cols-[2.25rem_minmax(0,1fr)_minmax(14rem,0.48fr)_auto] [&_a]:items-center [&_a]:gap-6 [&_a]:p-[clamp(1.35rem,3vw,2.25rem)] max-[800px]:[&_a]:grid-cols-[2.25rem_minmax(0,1fr)_auto] max-[800px]:[&_dl]:hidden [&_a>span]:grid [&_a>span]:size-9 [&_a>span]:place-items-center [&_a>span]:rounded-xl [&_a>span]:bg-violet-500/10 [&_a>span]:text-xs [&_a>span]:font-semibold [&_a>span]:text-violet-300 [&_small]:text-[11px] [&_small]:font-medium [&_small]:text-white/35 [&_h2]:my-2.5 [&_h2]:text-[clamp(1.35rem,2.5vw,2rem)] [&_h2]:font-semibold [&_h2]:tracking-tight [&_p]:m-0 [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-white/50 [&_dl]:m-0 [&_dl]:grid [&_dl]:gap-2 [&_dl_div]:grid [&_dl_div]:grid-cols-[1fr_auto] [&_dl_div]:gap-4 [&_dl_div]:rounded-xl [&_dl_div]:border [&_dl_div]:border-white/[0.04] [&_dl_div]:bg-white/[0.02] [&_dl_div]:px-3 [&_dl_div]:py-2.5 [&_dt]:text-[11px] [&_dt]:text-white/35 [&_dd]:m-0 [&_dd]:max-w-36 [&_dd]:truncate [&_dd]:text-right [&_dd]:text-[11px] [&_dd]:font-medium [&_dd]:capitalize [&_a>strong]:grid [&_a>strong]:size-9 [&_a>strong]:place-items-center [&_a>strong]:rounded-full [&_a>strong]:bg-white/[0.04] [&_a>strong]:text-sm [&_a>strong]:text-white/45 [&_a>strong]:transition-all [&_a:hover>strong]:bg-violet-500/15 [&_a:hover>strong]:text-violet-300",
  objectives:
    `${vectraStyles.card} mb-6 grid gap-8 [background-image:radial-gradient(circle_at_top_left,rgba(139,92,246,0.18),transparent_55%)] p-[clamp(1.5rem,4vw,3rem)] md:grid-cols-[0.42fr_1fr] [&>span]:inline-flex [&>span]:h-fit [&>span]:w-fit [&>span]:rounded-full [&>span]:border [&>span]:border-violet-400/20 [&>span]:bg-violet-400/[0.06] [&>span]:px-3 [&>span]:py-1.5 [&>span]:text-xs [&>span]:font-medium [&>span]:text-violet-300 [&_ol]:m-0 [&_ol]:grid [&_ol]:list-none [&_ol]:gap-3 [&_ol]:p-0 [&_li]:rounded-2xl [&_li]:border [&_li]:border-white/[0.04] [&_li]:bg-white/[0.025] [&_li]:p-4 [&_li]:text-sm [&_li]:leading-relaxed [&_li]:text-white/65`,
  progressError:
    "mb-5 flex items-center justify-between gap-6 rounded-2xl border border-amber-400/20 bg-amber-400/[0.05] p-4 max-[600px]:items-start max-[600px]:flex-col [&_span]:text-xs [&_span]:font-semibold [&_span]:text-amber-300 [&_p]:mt-1.5 [&_p]:mb-0 [&_p]:text-sm [&_p]:text-white/50 [&_button]:shrink-0 [&_button]:rounded-full [&_button]:border [&_button]:border-white/10 [&_button]:bg-white/[0.04] [&_button]:px-4 [&_button]:py-2.5 [&_button]:text-xs [&_button]:font-medium [&_button:hover]:bg-white/[0.08]",
  readerGrid:
    "grid grid-cols-[minmax(16rem,0.45fr)_minmax(0,1.3fr)] items-start gap-6 max-[800px]:grid-cols-1 [&_aside]:sticky [&_aside]:top-24 [&_aside]:rounded-3xl [&_aside]:border [&_aside]:border-white/[0.06] [&_aside]:bg-card/60 [&_aside]:p-5 [&_aside]:shadow-[0_24px_60px_-24px_rgba(0,0,0,0.55)] max-[800px]:[&_aside]:static [&_aside>span]:text-xs [&_aside>span]:font-medium [&_aside>span]:text-white/40 [&_aside>ol]:my-5 [&_aside>ol]:grid [&_aside>ol]:list-none [&_aside>ol]:gap-2 [&_aside>ol]:p-0 [&_aside_button]:grid [&_aside_button]:w-full [&_aside_button]:grid-cols-[2rem_1fr_auto] [&_aside_button]:items-center [&_aside_button]:gap-3 [&_aside_button]:rounded-2xl [&_aside_button]:border [&_aside_button]:border-transparent [&_aside_button]:bg-white/[0.02] [&_aside_button]:p-3 [&_aside_button]:text-left [&_aside_button]:transition-all [&_aside_button:hover]:border-white/[0.06] [&_aside_button:hover]:bg-white/[0.05] [&_aside_button[data-active=true]]:border-violet-400/20 [&_aside_button[data-active=true]]:bg-violet-500/10 [&_aside_button[data-active=true]_strong]:text-violet-200 [&_aside_button_span]:text-[11px] [&_aside_button_span]:text-white/35 [&_aside_small]:rounded-full [&_aside_small]:bg-emerald-400/10 [&_aside_small]:px-2 [&_aside_small]:py-1 [&_aside_small]:text-[10px] [&_aside_small]:font-medium [&_aside_small]:text-emerald-300 [&_aside_button_strong]:text-xs [&_aside_button_strong]:font-medium [&_aside_button_strong]:text-white/70 [&_aside>a]:inline-flex [&_aside>a]:rounded-full [&_aside>a]:bg-white/[0.04] [&_aside>a]:px-4 [&_aside>a]:py-2.5 [&_aside>a]:text-xs [&_aside>a]:font-medium [&_aside>a]:text-white/55 [&_aside>a:hover]:bg-white/[0.08] [&_aside>a:hover]:text-white",
  lesson:
    `${vectraStyles.card} min-w-0 p-[clamp(1.5rem,4vw,3rem)] [&_header]:flex [&_header]:justify-between [&_header]:gap-4 [&_header]:text-xs [&_header]:font-medium [&_header]:text-white/35 [&_h2]:mt-7 [&_h2]:mb-4 [&_h2]:max-w-[20ch] [&_h2]:text-[clamp(2rem,4vw,3.5rem)] [&_h2]:leading-[1.05] [&_h2]:font-semibold [&_h2]:tracking-tighter [&_footer]:mt-12 [&_footer]:flex [&_footer]:items-center [&_footer]:justify-between [&_footer]:gap-4 [&_footer]:rounded-2xl [&_footer]:border [&_footer]:border-white/[0.04] [&_footer]:bg-white/[0.02] [&_footer]:p-4 max-[600px]:[&_footer]:items-start max-[600px]:[&_footer]:flex-col [&_footer>span]:text-xs [&_footer>span]:font-medium [&_footer>span]:text-white/40 [&_footer_button]:rounded-full [&_footer_button]:border-0 [&_footer_button]:bg-gradient-to-r [&_footer_button]:from-[#C084FC] [&_footer_button]:to-[#6366F1] [&_footer_button]:px-5 [&_footer_button]:py-3 [&_footer_button]:text-sm [&_footer_button]:font-medium [&_footer_button]:text-white [&_footer_button]:transition-all [&_footer_button:hover]:scale-[1.02] [&_footer_button:active]:scale-[0.98] [&_footer_button:disabled]:opacity-50 [&_footer_p]:text-xs [&_footer_p]:text-red-300`,
  standaloneLesson:
    "grid gap-4 [&>a]:inline-flex [&>a]:w-fit [&>a]:rounded-full [&>a]:border [&>a]:border-white/10 [&>a]:bg-white/[0.04] [&>a]:px-5 [&>a]:py-3 [&>a]:text-sm [&>a]:font-medium [&>a]:text-white/70 [&>a]:transition-all [&>a:hover]:border-white/15 [&>a:hover]:bg-white/[0.08] [&>a:hover]:text-white",
  lessonSummary: "text-base leading-relaxed text-white/55",
  lessonBody:
    "mt-10 text-[15px] leading-7 text-white/70 [&_h2]:mt-10 [&_h2]:text-2xl [&_h2]:font-semibold [&_h2]:tracking-tight [&_h3]:mt-8 [&_h3]:text-xl [&_h3]:font-semibold [&_h4]:mt-8 [&_h4]:text-lg [&_h4]:font-semibold [&_a]:text-violet-300 [&_a:hover]:text-violet-200 [&_blockquote]:mx-0 [&_blockquote]:my-8 [&_blockquote]:rounded-2xl [&_blockquote]:border [&_blockquote]:border-violet-400/15 [&_blockquote]:bg-violet-500/[0.05] [&_blockquote]:p-5 [&_blockquote]:text-white/60 [&_pre]:max-w-full [&_pre]:overflow-x-auto [&_pre]:rounded-2xl [&_pre]:border [&_pre]:border-white/[0.05] [&_pre]:bg-black/30 [&_pre]:p-4",
  lessonQuiz:
    "mt-8 grid grid-cols-[minmax(8rem,0.35fr)_minmax(0,1fr)_auto] items-center gap-4 rounded-2xl border border-white/[0.05] bg-white/[0.025] p-5 max-[800px]:grid-cols-1 max-[800px]:items-start [&>span]:text-xs [&>span]:font-medium [&>span]:text-violet-300 [&_h3]:m-0 [&_h3]:text-lg [&_h3]:font-semibold [&_p]:mt-1.5 [&_p]:mb-0 [&_p]:text-xs [&_p]:leading-relaxed [&_p]:text-white/45 [&_a]:rounded-full [&_a]:border-0 [&_a]:bg-gradient-to-r [&_a]:from-[#C084FC] [&_a]:to-[#6366F1] [&_a]:px-5 [&_a]:py-3 [&_a]:text-xs [&_a]:font-medium [&_a]:text-white [&_a]:transition-all [&_a:hover]:scale-[1.02] [&_button]:rounded-full [&_button]:border [&_button]:border-white/10 [&_button]:bg-white/[0.04] [&_button]:px-5 [&_button]:py-3 [&_button]:text-xs [&_button]:font-medium [&_button:hover]:bg-white/[0.08]",
} as const;
