export const learningStyles = {
  catalog: "mx-auto max-w-[1400px]",
  course: "mx-auto max-w-[1400px]",
  hero:
    "grid grid-cols-[minmax(0,1.2fr)_minmax(18rem,0.55fr)] gap-[clamp(2rem,7vw,7rem)] py-[clamp(3rem,6vw,6rem)] max-[800px]:grid-cols-1 [&>span]:col-span-full [&>span]:font-sans [&>span]:text-[0.6rem] [&>span]:tracking-normal [&>span]:text-accent [&>span]:normal-case max-[800px]:[&>span]:col-span-1 [&_h1]:m-0 [&_h1]:text-[clamp(3rem,6vw,6rem)] [&_h1]:leading-[0.98] [&_h1]:font-semibold [&_h1]:tracking-normal [&_p]:m-0 [&_p]:self-end [&_p]:leading-[1.65] [&_p]:text-muted-foreground",
  courseHeader:
    "grid grid-cols-[minmax(0,1.2fr)_minmax(18rem,0.55fr)] gap-[clamp(2rem,7vw,7rem)] py-[clamp(3rem,7vw,7rem)] max-[800px]:grid-cols-1 [&_span]:font-sans [&_span]:text-[0.58rem] [&_span]:tracking-normal [&_span]:text-muted [&_span]:normal-case [&_h1]:m-0 [&_h1]:font-editorial [&_h1]:text-[clamp(2.75rem,5vw,5rem)] [&_h1]:leading-[0.88] [&_h1]:font-normal [&_h1]:tracking-normal [&_p]:m-0 [&_p]:self-end [&_p]:leading-[1.65] [&_p]:text-muted-foreground [&_dl]:m-0 [&_dl_div]:grid [&_dl_div]:grid-cols-2 [&_dl_div]:gap-4 [&_dl_div]:rounded-xl [&_dl_div]:bg-white/[0.025] [&_dl_div]:px-3 [&_dl_div]:py-3 [&_dd]:m-0 [&_dd]:text-right [&_dd]:text-[0.7rem] [&_dd]:capitalize",
  loading:
    "[&>span]:font-sans [&>span]:text-[0.58rem] [&>span]:tracking-normal [&>span]:text-muted [&>span]:normal-case [&_div]:mt-px [&_div]:h-22.5 [&_div]:animate-pulse [&_div]:bg-surface-muted",
  error:
    "flex min-h-90 flex-col items-start justify-center [&>span]:font-sans [&>span]:text-[0.58rem] [&>span]:tracking-normal [&>span]:text-muted [&>span]:normal-case [&_h2]:font-editorial [&_h2]:text-[clamp(2.3rem,4vw,4rem)] [&_h2]:font-normal [&_h2]:tracking-normal [&_p]:text-muted-foreground [&_button]:border [&_button]:border-border [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-sans [&_button]:text-[0.58rem] [&_button]:normal-case",
  empty:
    "flex min-h-90 flex-col items-start justify-center [&>span]:font-sans [&>span]:text-[0.58rem] [&>span]:tracking-normal [&>span]:text-muted [&>span]:normal-case [&_h2]:font-editorial [&_h2]:text-[clamp(2.3rem,4vw,4rem)] [&_h2]:font-normal [&_h2]:tracking-normal [&_p]:text-muted-foreground",
  courseLoading:
    "flex min-h-90 flex-col items-start justify-center [&>span]:font-sans [&>span]:text-[0.58rem] [&>span]:tracking-normal [&>span]:text-muted [&>span]:normal-case [&_h1]:font-editorial [&_h1]:text-[clamp(2.75rem,5vw,5rem)] [&_h1]:leading-[0.88] [&_h1]:font-normal [&_h1]:tracking-normal",
  courseList:
    "m-0 grid list-none gap-4 p-0 [&_li]:overflow-hidden [&_li]:rounded-3xl [&_li]:border [&_li]:border-white/[0.08] [&_li]:bg-surface/70 [&_a]:grid [&_a]:grid-cols-[2rem_minmax(0,1fr)_minmax(14rem,0.45fr)_auto] [&_a]:items-start [&_a]:gap-8 [&_a]:p-[clamp(1.5rem,3vw,3rem)] [&_a]:transition-all [&_a:hover]:bg-white/[0.06] max-[800px]:[&_a]:grid-cols-[2rem_1fr_auto] [&_span]:font-sans [&_span]:text-[0.7rem] [&_span]:text-accent [&_small]:font-sans [&_small]:text-[0.65rem] [&_small]:text-muted [&_h2]:my-2.5 [&_h2]:text-[clamp(1.6rem,3vw,2.5rem)] [&_h2]:font-semibold [&_p]:m-0 [&_p]:leading-[1.55] [&_p]:text-muted-foreground [&_dl]:m-0 max-[800px]:[&_dl]:hidden [&_dl_div]:grid [&_dl_div]:grid-cols-2 [&_dl_div]:gap-4 [&_dl_div]:rounded-xl [&_dl_div]:bg-white/[0.04] [&_dl_div]:px-3 [&_dl_div]:py-3 [&_dt]:text-[0.65rem] [&_dt]:text-muted [&_dd]:m-0 [&_dd]:text-right [&_dd]:text-[0.7rem] [&_dd]:capitalize",
  objectives:
    "grid grid-cols-[0.4fr_1fr] gap-12 rounded-3xl bg-gradient-to-br from-violet-600 to-indigo-600 p-[clamp(2rem,5vw,5rem)] text-white shadow-xl shadow-violet-950/20 max-[800px]:grid-cols-1 [&>span]:text-sm [&_ol]:m-0 [&_ol]:grid [&_ol]:gap-3 [&_ol]:pl-5 [&_li]:rounded-2xl [&_li]:bg-white/10 [&_li]:p-4 [&_li]:leading-[1.55]",
  progressError:
    "mb-4 flex items-center justify-between gap-8 rounded-2xl border border-warning/30 bg-warning/5 p-4 [&_span]:text-sm [&_span]:text-warning [&_p]:mt-1.5 [&_p]:text-sm [&_p]:text-muted-foreground [&_button]:rounded-xl [&_button]:border [&_button]:border-border [&_button]:bg-transparent [&_button]:p-3 [&_button]:text-sm",
  readerGrid:
    "grid grid-cols-[minmax(16rem,0.45fr)_minmax(0,1.3fr)] items-start gap-5 max-[800px]:grid-cols-1 [&_aside]:sticky [&_aside]:top-24 [&_aside]:rounded-3xl [&_aside]:border [&_aside]:border-white/[0.08] [&_aside]:bg-surface/70 [&_aside]:p-6 max-[800px]:[&_aside]:static [&_aside>span]:text-sm [&_aside>span]:text-muted [&_aside>ol]:my-5 [&_aside>ol]:grid [&_aside>ol]:list-none [&_aside>ol]:gap-2 [&_aside>ol]:p-0 [&_aside_button]:grid [&_aside_button]:w-full [&_aside_button]:grid-cols-[2rem_1fr_auto] [&_aside_button]:items-start [&_aside_button]:gap-3 [&_aside_button]:rounded-2xl [&_aside_button]:border-0 [&_aside_button]:bg-white/[0.03] [&_aside_button]:p-3 [&_aside_button]:text-left [&_aside_button]:transition-colors [&_aside_button:hover]:bg-white/[0.07] [&_aside_button[data-active=true]]:bg-violet-500/15 [&_aside_button[data-active=true]_strong]:text-accent [&_aside_button_span]:text-[0.65rem] [&_aside_button_span]:text-muted [&_aside_small]:text-[0.65rem] [&_aside_small]:text-muted [&_aside_button_strong]:text-[0.75rem] [&_aside_button_strong]:font-semibold [&_aside>a]:text-[0.7rem] [&_aside>a]:text-muted",
  lesson:
    "min-w-0 rounded-3xl border border-white/[0.08] bg-surface/60 p-[clamp(2rem,5vw,5rem)] [&_header]:flex [&_header]:justify-between [&_header]:text-sm [&_header]:text-muted [&_h2]:my-8 [&_h2]:mb-4 [&_h2]:text-[clamp(2.2rem,5vw,4.5rem)] [&_h2]:leading-[1] [&_h2]:font-semibold [&_footer]:mt-16 [&_footer]:flex [&_footer]:items-center [&_footer]:justify-between [&_footer]:gap-4 [&_footer]:rounded-2xl [&_footer]:bg-white/[0.04] [&_footer]:p-4 [&_footer>span]:text-sm [&_footer>span]:text-muted [&_footer_button]:rounded-xl [&_footer_button]:border-0 [&_footer_button]:bg-gradient-to-r [&_footer_button]:from-violet-500 [&_footer_button]:to-indigo-500 [&_footer_button]:p-3 [&_footer_button]:text-sm [&_footer_button]:text-white [&_footer_p]:text-[0.7rem] [&_footer_p]:text-danger",
  standaloneLesson:
    "grid gap-4 rounded-3xl border border-white/[0.08] bg-surface/60 p-3 [&>a]:block [&>a]:rounded-2xl [&>a]:bg-white/[0.04] [&>a]:p-4 [&>a]:text-sm [&>a:hover]:bg-white/[0.08]",
  lessonSummary: "text-base leading-[1.65] text-muted-foreground",
  lessonBody:
    "mt-12  pt-8 leading-7 [&_h2]:mt-10 [&_h2]:font-editorial [&_h2]:font-normal [&_h2]:tracking-normal [&_h3]:mt-10 [&_h3]:font-editorial [&_h3]:font-normal [&_h3]:tracking-normal [&_h4]:mt-10 [&_h4]:font-editorial [&_h4]:font-normal [&_h4]:tracking-normal [&_blockquote]:ml-0 [&_blockquote]:border-l-2 [&_blockquote]:border-accent [&_blockquote]:pl-6 [&_blockquote]:text-muted-foreground [&_pre]:max-w-full [&_pre]:overflow-x-auto [&_pre]:bg-surface-muted [&_pre]:p-4",
  lessonQuiz:
    "mt-8 grid grid-cols-[minmax(8rem,0.35fr)_minmax(0,1fr)_auto] items-center gap-4  pt-8 max-[800px]:grid-cols-1 max-[800px]:items-start [&>span]:font-sans [&>span]:text-[0.58rem] [&>span]:tracking-normal [&>span]:text-muted [&>span]:normal-case [&_h3]:m-0 [&_h3]:font-editorial [&_h3]:text-[1.7rem] [&_h3]:font-normal [&_p]:mt-1.5 [&_p]:text-[0.72rem] [&_p]:text-muted-foreground [&_a]:border [&_a]:border-border-strong [&_a]:bg-transparent [&_a]:p-3 [&_a]:font-sans [&_a]:text-[0.58rem] [&_a]:normal-case [&_button]:border [&_button]:border-border-strong [&_button]:bg-transparent [&_button]:p-3 [&_button]:font-sans [&_button]:text-[0.58rem] [&_button]:normal-case",
} as const;
